import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

// Inline catalog — backend functions cannot import local files
const artifacts = [
  { artifactId: 'davids-sling', name: "David's Sling", rarity: 'rare', xpCost: 3500, category: 'weapon', scripture: { reference: '1 Samuel 17:40', passage: "And he took his staff in his hand, and chose him five smooth stones out of the brook, and put them in a shepherd's bag which he had, even in a scrip; and his sling was in his hand." }, lore: "The humble sling used by young David to defeat the giant Goliath. A symbol of faith over strength.", visualDescription: 'A weathered leather sling with five smooth, glowing stones.' },
  { artifactId: 'samsons-jawbone', name: "Samson's Jawbone", rarity: 'legendary', xpCost: 9000, category: 'weapon', scripture: { reference: 'Judges 15:15-16', passage: "And he found a new jawbone of an ass, and put forth his hand, and took it, and slew a thousand men therewith." }, lore: "An unconventional weapon wielded by Samson in his greatest victory.", visualDescription: 'A weathered jawbone etched with ancient power and Hebrew letters.' },
  { artifactId: 'sauls-spear', name: "Saul's Spear", rarity: 'epic', xpCost: 6500, category: 'weapon', scripture: { reference: '1 Samuel 18:10-11', passage: "And it came to pass on the morrow, that the evil spirit from God came upon Saul...and there was a javelin in Saul's hand." }, lore: "The spear of King Saul, a symbol of royal authority and the burden of earthly power.", visualDescription: 'A bronze-tipped spear with royal engravings.' },
  { artifactId: 'jonathans-bow', name: "Jonathan's Bow", rarity: 'epic', xpCost: 7000, category: 'weapon', scripture: { reference: '1 Samuel 20:20-22', passage: "And I will shoot three arrows on the side thereof, as though I shot at a mark." }, lore: "Jonathan's bow, used to signal his covenant with David. A symbol of loyalty.", visualDescription: 'A noble wooden bow with silver inlays.' },
  { artifactId: 'goliaths-sword', name: 'The Sword of Goliath', rarity: 'mythic', xpCost: 15000, category: 'weapon', xpBoost: 1.15, scripture: { reference: '1 Samuel 21:9', passage: "The sword of Goliath the Philistine, whom thou slewest in the valley of Elah." }, lore: "The massive iron sword of the giant Goliath, defeated by David's faith.", visualDescription: 'A colossal iron blade, notched and weathered from ancient battles.' },
  { artifactId: 'moses-staff', name: "Moses' Staff", rarity: 'mythic', xpCost: 18000, category: 'weapon', xpBoost: 1.20, scripture: { reference: 'Exodus 4:17', passage: "And thou shalt take this rod in thine hand, wherewith thou shalt do signs." }, lore: "The staff through which God parted the Red Sea.", visualDescription: 'A radiant staff crackling with divine energy.' },
  { artifactId: 'elijah-staff', name: "Elijah's Staff", rarity: 'epic', xpCost: 6000, category: 'weapon', scripture: { reference: '2 Kings 4:29', passage: "And he said to Gehazi, Gird up thy loins, and take my staff in thine hand." }, lore: "The staff of the prophet Elijah, instrument of miracles.", visualDescription: 'A gnarled wooden staff with glowing prophetic runes.' },
  { artifactId: 'peter-keys', name: "Peter's Keys", rarity: 'rare', xpCost: 2500, category: 'weapon', scripture: { reference: 'Matthew 16:19', passage: "And I will give unto thee the keys of the kingdom of heaven." }, lore: "The symbolic keys given to Peter, representing spiritual authority.", visualDescription: 'Two ornate golden keys intertwined with radiant light.' },
  { artifactId: 'shield-of-faith', name: 'The Shield of Faith', rarity: 'legendary', xpCost: 10000, category: 'weapon', xpBoost: 1.10, scripture: { reference: 'Ephesians 6:16', passage: "Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked." }, lore: "Represents spiritual protection and unwavering belief.", visualDescription: 'A radiant shield inscribed with FAITH.' },
  { artifactId: 'sword-of-spirit', name: 'The Sword of the Spirit', rarity: 'legendary', xpCost: 11000, category: 'weapon', xpBoost: 1.12, scripture: { reference: 'Ephesians 6:17', passage: "And take the helmet of salvation, and the sword of the Spirit, which is the word of God." }, lore: "The ultimate spiritual weapon — the Word of God itself.", visualDescription: 'A glowing ethereal blade inscribed with scripture.' },
  { artifactId: 'ark-covenant', name: 'The Ark of the Covenant', rarity: 'mythic', xpCost: 25000, category: 'temple', xpBoost: 1.25, scripture: { reference: 'Exodus 25:10-16', passage: "And they shall make an ark of shittim wood...thou shalt overlay it with pure gold." }, lore: "The holiest object in Israel, containing the tablets of the law.", visualDescription: 'A golden chest radiating divine presence with cherubim on the mercy seat.' },
  { artifactId: 'golden-lampstand', name: 'The Golden Lampstand', rarity: 'rare', xpCost: 3000, category: 'temple', scripture: { reference: 'Exodus 25:31-37', passage: "And thou shalt make a candlestick of pure gold: of beaten work shall the candlestick be made." }, lore: "The seven-branched menorah representing God's light.", visualDescription: 'A golden candelabra with seven branches and eternal flames.' },
  { artifactId: 'altar-incense', name: 'The Altar of Incense', rarity: 'epic', xpCost: 7000, category: 'temple', scripture: { reference: 'Exodus 30:1-8', passage: "And thou shalt make an altar to burn incense upon: of shittim wood shalt thou make it." }, lore: "Where prayers ascend as fragrant incense to heaven.", visualDescription: 'An ornate golden altar with rising holy smoke.' },
  { artifactId: 'stone-tablets', name: 'The Stone Tablets', rarity: 'epic', xpCost: 8500, category: 'temple', xpBoost: 1.14, scripture: { reference: 'Exodus 31:18', passage: "Two tables of testimony, tables of stone, written with the finger of God." }, lore: "The Ten Commandments inscribed by God's own finger.", visualDescription: 'Two stone tablets glowing with divine script.' },
  { artifactId: 'temple-veil', name: 'The Temple Veil', rarity: 'legendary', xpCost: 12000, category: 'temple', xpBoost: 1.18, scripture: { reference: 'Matthew 27:51', passage: "And, behold, the veil of the temple was rent in twain from the top to the bottom." }, lore: "The veil torn at Christ's crucifixion, symbolizing open access to God.", visualDescription: 'A shimmering purple cloth torn from top to bottom.' },
  { artifactId: 'priestly-breastplate', name: "The High Priest's Breastplate", rarity: 'mythic', xpCost: 20000, category: 'temple', xpBoost: 1.22, scripture: { reference: 'Exodus 28:15-30', passage: "And thou shalt make the breastplate of judgment with cunning work." }, lore: "Set with 12 gemstones representing the tribes of Israel.", visualDescription: 'A jeweled breastplate gleaming with twelve precious stones.' },
  { artifactId: 'bronze-serpent', name: 'The Bronze Serpent', rarity: 'rare', xpCost: 4000, category: 'temple', scripture: { reference: 'Numbers 21:8-9', passage: "Make thee a fiery serpent, and set it upon a pole: every one that is bitten, when he looketh upon it, shall live." }, lore: "Moses' bronze serpent, a foreshadow of Christ lifted up for healing.", visualDescription: 'A coiled bronze serpent mounted on a wooden pole.' },
  { artifactId: 'urim-thummim', name: 'The Urim and Thummim', rarity: 'legendary', xpCost: 13000, category: 'temple', xpBoost: 1.16, scripture: { reference: 'Exodus 28:30', passage: "And thou shalt put in the breastplate of judgment the Urim and the Thummim." }, lore: "Sacred objects used by the High Priest to discern God's will.", visualDescription: 'Two luminous stones pulsing with divine insight.' },
  { artifactId: 'table-shewbread', name: 'The Table of Shewbread', rarity: 'epic', xpCost: 7500, category: 'temple', scripture: { reference: 'Exodus 25:23-30', passage: "Thou shalt also make a table of shittim wood." }, lore: "A sacred table representing provision and God's constant care.", visualDescription: 'A wooden table overlaid with pure gold, set with twelve loaves.' },
  { artifactId: 'golden-calf', name: 'The Golden Calf', rarity: 'common', xpCost: 1000, category: 'temple', scripture: { reference: 'Exodus 32:4', passage: "And he fashioned it with a graving tool, after he had made it a molten calf." }, lore: "A cautionary artifact representing human weakness and idolatry.", visualDescription: 'A small golden calf statue.' },
  { artifactId: 'isaiah-scroll', name: "Isaiah's Scroll", rarity: 'legendary', xpCost: 11000, category: 'prophetic', xpBoost: 1.13, scripture: { reference: 'Isaiah 6:8', passage: "Also I heard the voice of the Lord, saying, Whom shall I send? Then said I, Here am I; send me." }, lore: "The prophetic scroll containing the greatest messianic prophecies.", visualDescription: 'An ancient scroll glowing with prophetic light.' },
  { artifactId: 'jeremiahs-clay', name: "Jeremiah's Potter's Clay", rarity: 'common', xpCost: 800, category: 'prophetic', scripture: { reference: 'Jeremiah 18:6', passage: "As the clay is in the potter's hand, so are ye in mine hand, saith the Lord." }, lore: "Clay from the potter's house, illustrating God's sovereignty.", visualDescription: "A lump of red clay bearing the potter's marks." },
  { artifactId: 'elijahs-mantle', name: "Elijah's Mantle", rarity: 'legendary', xpCost: 12000, category: 'prophetic', xpBoost: 1.17, scripture: { reference: '2 Kings 2:13-14', passage: "He took up also the mantle of Elijah that fell from him." }, lore: "The prophetic mantle passed from Elijah to Elisha, doubling his power.", visualDescription: 'A weathered cloak crackling with transferred anointing.' },
  { artifactId: 'ezekiels-wheel', name: "Ezekiel's Wheel", rarity: 'mythic', xpCost: 22000, category: 'prophetic', xpBoost: 1.23, scripture: { reference: 'Ezekiel 1:16', passage: "Their appearance was as it were a wheel in the middle of a wheel." }, lore: "The mysterious heavenly wheels of Ezekiel's vision.", visualDescription: 'A glowing, spinning wheel within a wheel of celestial beryl.' },
  { artifactId: 'daniels-lions', name: "Daniel's Lion's Den Stone", rarity: 'epic', xpCost: 8000, category: 'prophetic', scripture: { reference: 'Daniel 6:17', passage: "And a stone was brought, and laid upon the mouth of the den." }, lore: "The stone that sealed Daniel in and witnessed his miraculous deliverance.", visualDescription: "A heavy stone bearing the king's seal, cracked by divine intervention." },
  { artifactId: 'jonahs-fish', name: "Jonah's Whale Tooth", rarity: 'rare', xpCost: 3500, category: 'prophetic', scripture: { reference: 'Jonah 1:17', passage: "Now the Lord had prepared a great fish to swallow up Jonah." }, lore: "A tooth from the great fish — a sign of death, burial, and resurrection.", visualDescription: 'A massive whale tooth with the silhouette of a man within.' },
  { artifactId: 'burning-bush', name: 'The Burning Bush', rarity: 'mythic', xpCost: 19000, category: 'prophetic', xpBoost: 1.20, scripture: { reference: 'Exodus 3:2', passage: "The bush burned with fire, and the bush was not consumed." }, lore: "The site of God's first revelation to Moses. A fire that burns without consuming.", visualDescription: 'A small thorny bush ablaze with eternal divine fire.' },
  { artifactId: 'hoseas-scroll', name: "Hosea's Scroll", rarity: 'rare', xpCost: 2800, category: 'prophetic', scripture: { reference: 'Hosea 6:6', passage: "For I desired mercy, and not sacrifice; and the knowledge of God more than burnt offerings." }, lore: "A prophet whose life became a parable of God's unfailing love.", visualDescription: 'A worn papyrus scroll sealed with a cord of love.' },
  { artifactId: 'amos-plumb-line', name: "Amos' Plumb Line", rarity: 'common', xpCost: 1200, category: 'prophetic', scripture: { reference: 'Amos 7:7-8', passage: "Behold, the Lord stood upon a wall made by a plumbline, with a plumbline in his hand." }, lore: "God's measuring line of righteousness and justice.", visualDescription: 'A simple weighted string used to measure straightness.' },
  { artifactId: 'zechariahs-lamp', name: "Zechariah's Golden Lamp", rarity: 'epic', xpCost: 8000, category: 'prophetic', xpBoost: 1.11, scripture: { reference: 'Zechariah 4:2', passage: "Behold a candlestick all of gold, with a bowl upon the top of it, and his seven lamps thereon." }, lore: "The golden lampstand from Zechariah's vision — the Spirit's anointing.", visualDescription: 'A golden lamp with seven wicks, glowing with prophetic fire.' },
  { artifactId: 'solomons-crown', name: "Solomon's Crown", rarity: 'mythic', xpCost: 21000, category: 'royal', xpBoost: 1.19, scripture: { reference: 'Song of Solomon 3:11', passage: "Behold king Solomon with the crown wherewith his mother crowned him." }, lore: "The crown of the wisest king who ever lived.", visualDescription: 'A gleaming golden crown set with precious gems from the east.' },
  { artifactId: 'davids-harp', name: "David's Harp", rarity: 'legendary', xpCost: 10500, category: 'royal', xpBoost: 1.13, scripture: { reference: '1 Samuel 16:23', passage: "David took an harp, and played with his hand: so Saul was refreshed." }, lore: "The harp of the shepherd-king whose music drove away evil spirits.", visualDescription: 'A beautifully carved wooden harp strung with golden strings.' },
  { artifactId: 'queens-scepter', name: "Esther's Scepter", rarity: 'legendary', xpCost: 11500, category: 'royal', xpBoost: 1.16, scripture: { reference: 'Esther 5:2', passage: "The king held out to Esther the golden sceptre that was in his hand." }, lore: "The scepter extended to Esther — a symbol of grace and favor.", visualDescription: 'An elegant golden scepter radiating royal grace.' },
  { artifactId: 'solomons-ring', name: "Solomon's Signet Ring", rarity: 'epic', xpCost: 9000, category: 'royal', scripture: { reference: 'Ecclesiastes 1:1', passage: "The words of the Preacher, the son of David, king in Jerusalem." }, lore: "The seal ring of Solomon, used to stamp royal decrees.", visualDescription: 'A heavy golden ring engraved with a six-pointed star.' },
  { artifactId: 'davidic-throne', name: "A Stone from David's Throne", rarity: 'epic', xpCost: 8500, category: 'royal', xpBoost: 1.12, scripture: { reference: '2 Samuel 7:16', passage: "Thy throne shall be established for ever." }, lore: "A fragment from the eternal throne promised to David.", visualDescription: 'A polished stone bearing the inscription of an eternal covenant.' },
  { artifactId: 'josephs-coat', name: "Joseph's Coat of Many Colors", rarity: 'legendary', xpCost: 13000, category: 'royal', xpBoost: 1.15, scripture: { reference: 'Genesis 37:3', passage: "He made him a coat of many colours." }, lore: "The beloved coat that sparked jealousy but led Joseph to his divine destiny.", visualDescription: 'A dazzling multi-colored robe shimmering with every hue.' },
  { artifactId: 'cyrus-decree', name: "Cyrus' Royal Decree", rarity: 'rare', xpCost: 4500, category: 'royal', scripture: { reference: 'Ezra 1:2', passage: "The Lord God of heaven hath given me all the kingdoms of the earth." }, lore: "The remarkable decree of Cyrus the Great, who freed God's people.", visualDescription: 'A clay tablet inscribed with cuneiform bearing the royal seal.' },
  { artifactId: 'nehemiahs-cup', name: "Nehemiah's Cupbearer's Cup", rarity: 'common', xpCost: 1500, category: 'royal', scripture: { reference: 'Nehemiah 1:11', passage: "For I was the king's cupbearer." }, lore: "The humble cup of the man who rebuilt Jerusalem's walls through prayer.", visualDescription: 'A simple golden cup, scratched from years of faithful service.' },
  { artifactId: 'absalom-hair', name: "Absalom's Locks", rarity: 'common', xpCost: 900, category: 'royal', scripture: { reference: '2 Samuel 14:26', passage: "He weighed the hair of his head at two hundred shekels." }, lore: "The famous locks of Absalom — beauty that became his downfall.", visualDescription: 'Silky dark hair in a golden case, beautiful yet tragic.' },
  { artifactId: 'jeroboam-altar', name: "Jeroboam's Altar Fragment", rarity: 'rare', xpCost: 2000, category: 'royal', scripture: { reference: '1 Kings 12:28-30', passage: "Whereupon the king took counsel, and made two calves of gold." }, lore: "A piece of the unauthorized altar — a sobering reminder of compromise.", visualDescription: 'A broken stone altar fragment, cracked by divine judgment.' },
  { artifactId: 'crown-of-thorns', name: 'The Crown of Thorns', rarity: 'mythic', xpCost: 30000, category: 'testament', xpBoost: 1.30, scripture: { reference: 'Matthew 27:29', passage: "And when they had platted a crown of thorns, they put it upon his head." }, lore: "The ultimate artifact. The crown placed on Jesus before His crucifixion.", visualDescription: 'A crown of twisted thorns radiating redemptive light.' },
  { artifactId: 'lords-cup', name: "The Lord's Cup", rarity: 'mythic', xpCost: 28000, category: 'testament', xpBoost: 1.28, scripture: { reference: 'Matthew 26:27-28', passage: "This is my blood of the new testament, which is shed for many for the remission of sins." }, lore: "The cup of the Last Supper — the new covenant in His blood.", visualDescription: 'A simple wooden cup radiating eternal covenant light.' },
  { artifactId: 'five-loaves', name: 'The Five Loaves and Two Fish', rarity: 'legendary', xpCost: 11000, category: 'testament', xpBoost: 1.14, scripture: { reference: 'John 6:9-11', passage: "There is a lad here, which hath five barley loaves, and two small fishes." }, lore: "The lunch of a boy that fed five thousand through multiplication.", visualDescription: 'A small basket of glowing loaves and fish, endlessly multiplying.' },
  { artifactId: 'emmaus-bread', name: 'The Bread of Emmaus', rarity: 'epic', xpCost: 9500, category: 'testament', xpBoost: 1.13, scripture: { reference: 'Luke 24:30-31', passage: "He took bread, and blessed it, and brake, and gave to them. And their eyes were opened." }, lore: "The bread broken by the risen Christ — the moment of recognition.", visualDescription: 'A glowing piece of broken bread, warm and comforting.' },
  { artifactId: 'widows-mite', name: "The Widow's Mite", rarity: 'common', xpCost: 500, category: 'testament', scripture: { reference: 'Mark 12:42-44', passage: "This poor widow hath cast more in, than all they which have cast into the treasury." }, lore: "Two smallest coins ever given, yet the greatest offering in God's sight.", visualDescription: 'Two tiny ancient coins, worn smooth by faithful hands.' },
  { artifactId: 'alabaster-jar', name: "Mary's Alabaster Jar", rarity: 'legendary', xpCost: 12500, category: 'testament', xpBoost: 1.17, scripture: { reference: 'Mark 14:3', passage: "There came a woman having an alabaster box of ointment of spikenard very precious." }, lore: "The jar of costly perfume poured over Jesus in extravagant worship.", visualDescription: 'A broken alabaster jar still fragrant with precious spikenard.' },
  { artifactId: 'fishing-net', name: "The Disciples' Fishing Net", rarity: 'common', xpCost: 1200, category: 'testament', scripture: { reference: 'Matthew 4:19-20', passage: "Follow me, and I will make you fishers of men. And they straightway left their nets." }, lore: "The nets left behind by Peter and Andrew — the cost of discipleship.", visualDescription: 'Old fishing nets, still damp, dropped on the shore.' },
  { artifactId: 'prodigal-ring', name: "The Father's Ring", rarity: 'epic', xpCost: 8000, category: 'testament', xpBoost: 1.11, scripture: { reference: 'Luke 15:22', passage: "Put a ring on his hand, and shoes on his feet." }, lore: "The ring placed on the prodigal son's hand — restored sonship and grace.", visualDescription: 'A golden family signet ring, given in joyful restoration.' },
  { artifactId: 'mustard-seed', name: 'The Mustard Seed', rarity: 'common', xpCost: 600, category: 'testament', scripture: { reference: 'Matthew 17:20', passage: "If ye have faith as a grain of mustard seed...nothing shall be impossible unto you." }, lore: "The tiniest seed representing the mightiest faith.", visualDescription: 'A single tiny mustard seed in a crystal vial.' },
  { artifactId: 'revelation-scroll', name: "John's Revelation Scroll", rarity: 'mythic', xpCost: 23000, category: 'testament', xpBoost: 1.22, scripture: { reference: 'Revelation 1:3', passage: "Blessed is he that readeth, and they that hear the words of this prophecy." }, lore: "The final prophetic scroll — visions of the end and the eternal kingdom.", visualDescription: 'A sealed scroll with seven seals, glowing with apocalyptic light.' },
];

const RARITY_ORDER = { mythic: 0, legendary: 1, epic: 2, rare: 3, common: 4 };

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const user = await base44.auth.me();
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await req.json().catch(() => ({}));
  const { rarity, category, search } = body;

  let filtered = [...artifacts];
  if (rarity) filtered = filtered.filter(a => a.rarity === rarity);
  if (category) filtered = filtered.filter(a => a.category === category);
  if (search?.trim()) {
    const q = search.toLowerCase();
    filtered = filtered.filter(a => a.name.toLowerCase().includes(q) || a.lore.toLowerCase().includes(q));
  }
  filtered.sort((a, b) => RARITY_ORDER[a.rarity] - RARITY_ORDER[b.rarity]);

  return Response.json({ success: true, artifacts: filtered, total: filtered.length });
});