/**
 * Character-focused Bible reading plans
 * Each character has a curated list of chapters in canonical order
 */
export const CHARACTER_LIBRARY = {
  Abraham: [
    { bookName: 'Genesis', chapter: 12 },
    { bookName: 'Genesis', chapter: 13 },
    { bookName: 'Genesis', chapter: 14 },
    { bookName: 'Genesis', chapter: 15 },
    { bookName: 'Genesis', chapter: 16 },
    { bookName: 'Genesis', chapter: 17 },
    { bookName: 'Genesis', chapter: 18 },
    { bookName: 'Genesis', chapter: 19 },
    { bookName: 'Genesis', chapter: 20 },
    { bookName: 'Genesis', chapter: 21 },
    { bookName: 'Genesis', chapter: 22 },
    { bookName: 'Genesis', chapter: 23 },
    { bookName: 'Genesis', chapter: 24 },
    { bookName: 'Genesis', chapter: 25 },
  ],
  
  Job: [
    { bookName: 'Job', chapter: 1 },
    { bookName: 'Job', chapter: 2 },
    { bookName: 'Job', chapter: 3 },
    { bookName: 'Job', chapter: 4 },
    { bookName: 'Job', chapter: 5 },
    { bookName: 'Job', chapter: 6 },
    { bookName: 'Job', chapter: 7 },
    { bookName: 'Job', chapter: 8 },
    { bookName: 'Job', chapter: 9 },
    { bookName: 'Job', chapter: 10 },
    { bookName: 'Job', chapter: 11 },
    { bookName: 'Job', chapter: 12 },
    { bookName: 'Job', chapter: 13 },
    { bookName: 'Job', chapter: 14 },
    { bookName: 'Job', chapter: 28 },
    { bookName: 'Job', chapter: 38 },
    { bookName: 'Job', chapter: 39 },
    { bookName: 'Job', chapter: 40 },
    { bookName: 'Job', chapter: 41 },
    { bookName: 'Job', chapter: 42 },
  ],
  
  Joseph: [
    { bookName: 'Genesis', chapter: 37 },
    { bookName: 'Genesis', chapter: 39 },
    { bookName: 'Genesis', chapter: 40 },
    { bookName: 'Genesis', chapter: 41 },
    { bookName: 'Genesis', chapter: 42 },
    { bookName: 'Genesis', chapter: 43 },
    { bookName: 'Genesis', chapter: 44 },
    { bookName: 'Genesis', chapter: 45 },
    { bookName: 'Genesis', chapter: 46 },
    { bookName: 'Genesis', chapter: 47 },
    { bookName: 'Genesis', chapter: 50 },
  ],
  
  Moses: [
    { bookName: 'Exodus', chapter: 2 },
    { bookName: 'Exodus', chapter: 3 },
    { bookName: 'Exodus', chapter: 4 },
    { bookName: 'Exodus', chapter: 5 },
    { bookName: 'Exodus', chapter: 6 },
    { bookName: 'Exodus', chapter: 7 },
    { bookName: 'Exodus', chapter: 12 },
    { bookName: 'Exodus', chapter: 14 },
    { bookName: 'Exodus', chapter: 15 },
    { bookName: 'Exodus', chapter: 19 },
    { bookName: 'Exodus', chapter: 20 },
    { bookName: 'Exodus', chapter: 32 },
    { bookName: 'Exodus', chapter: 33 },
    { bookName: 'Exodus', chapter: 34 },
    { bookName: 'Numbers', chapter: 11 },
    { bookName: 'Numbers', chapter: 12 },
    { bookName: 'Numbers', chapter: 13 },
    { bookName: 'Numbers', chapter: 14 },
    { bookName: 'Numbers', chapter: 20 },
    { bookName: 'Deuteronomy', chapter: 34 },
  ],
  
  Joshua: [
    { bookName: 'Joshua', chapter: 1 },
    { bookName: 'Joshua', chapter: 2 },
    { bookName: 'Joshua', chapter: 3 },
    { bookName: 'Joshua', chapter: 4 },
    { bookName: 'Joshua', chapter: 5 },
    { bookName: 'Joshua', chapter: 6 },
    { bookName: 'Joshua', chapter: 7 },
    { bookName: 'Joshua', chapter: 8 },
    { bookName: 'Joshua', chapter: 10 },
    { bookName: 'Joshua', chapter: 23 },
    { bookName: 'Joshua', chapter: 24 },
  ],
  
  David: [
    { bookName: '1 Samuel', chapter: 16 },
    { bookName: '1 Samuel', chapter: 17 },
    { bookName: '1 Samuel', chapter: 18 },
    { bookName: '1 Samuel', chapter: 19 },
    { bookName: '1 Samuel', chapter: 20 },
    { bookName: '1 Samuel', chapter: 24 },
    { bookName: '1 Samuel', chapter: 26 },
    { bookName: '2 Samuel', chapter: 5 },
    { bookName: '2 Samuel', chapter: 6 },
    { bookName: '2 Samuel', chapter: 7 },
    { bookName: '2 Samuel', chapter: 11 },
    { bookName: '2 Samuel', chapter: 12 },
    { bookName: '2 Samuel', chapter: 15 },
    { bookName: '1 Kings', chapter: 2 },
    { bookName: 'Psalms', chapter: 23 },
    { bookName: 'Psalms', chapter: 51 },
    { bookName: 'Psalms', chapter: 63 },
    { bookName: 'Psalms', chapter: 89 },
  ],
  
  Elijah: [
    { bookName: '1 Kings', chapter: 17 },
    { bookName: '1 Kings', chapter: 18 },
    { bookName: '1 Kings', chapter: 19 },
    { bookName: '1 Kings', chapter: 21 },
    { bookName: '2 Kings', chapter: 1 },
    { bookName: '2 Kings', chapter: 2 },
  ],
  
  Daniel: [
    { bookName: 'Daniel', chapter: 1 },
    { bookName: 'Daniel', chapter: 2 },
    { bookName: 'Daniel', chapter: 3 },
    { bookName: 'Daniel', chapter: 4 },
    { bookName: 'Daniel', chapter: 5 },
    { bookName: 'Daniel', chapter: 6 },
    { bookName: 'Daniel', chapter: 7 },
    { bookName: 'Daniel', chapter: 9 },
    { bookName: 'Daniel', chapter: 10 },
    { bookName: 'Daniel', chapter: 12 },
  ],
  
  Peter: [
    { bookName: 'Matthew', chapter: 4 },
    { bookName: 'Matthew', chapter: 14 },
    { bookName: 'Matthew', chapter: 16 },
    { bookName: 'Matthew', chapter: 17 },
    { bookName: 'Matthew', chapter: 26 },
    { bookName: 'John', chapter: 13 },
    { bookName: 'John', chapter: 18 },
    { bookName: 'John', chapter: 21 },
    { bookName: 'Acts', chapter: 2 },
    { bookName: 'Acts', chapter: 3 },
    { bookName: 'Acts', chapter: 4 },
    { bookName: 'Acts', chapter: 10 },
    { bookName: '1 Peter', chapter: 1 },
    { bookName: '1 Peter', chapter: 2 },
    { bookName: '1 Peter', chapter: 5 },
  ],
  
  Paul: [
    { bookName: 'Acts', chapter: 9 },
    { bookName: 'Acts', chapter: 13 },
    { bookName: 'Acts', chapter: 16 },
    { bookName: 'Acts', chapter: 17 },
    { bookName: 'Acts', chapter: 20 },
    { bookName: 'Acts', chapter: 22 },
    { bookName: 'Acts', chapter: 26 },
    { bookName: 'Acts', chapter: 27 },
    { bookName: 'Acts', chapter: 28 },
    { bookName: 'Romans', chapter: 8 },
    { bookName: '1 Corinthians', chapter: 13 },
    { bookName: 'Ephesians', chapter: 6 },
    { bookName: 'Philippians', chapter: 4 },
    { bookName: '2 Timothy', chapter: 4 },
  ],
};