/**
 * Character-focused Bible reading plans
 * Each character follows a 5-section historical deep dive format:
 * 1. Formation & Early Context
 * 2. Defining Test of Faith
 * 3. Calling & Commissioning
 * 4. Leadership / Ministry Narrative
 * 5. Legacy & Later Remembrance
 */

export const CHARACTER_LIBRARY = {
  Abraham: {
    iconKey: 'stars',
    accentColorKey: 'blue',
    hook: 'Called out. Set apart. Walking by faith.',
    description: "Follow Abraham from God's call out of Ur through the covenant promises that shaped Israel and the world. This deep dive traces his faith, obedience, failures, and lasting legacy.",
    sections: [
      {
        title: 'Formation & Early Context',
        chapters: [
          { bookName: 'Genesis', chapter: 11 },
          { bookName: 'Genesis', chapter: 12 },
        ]
      },
      {
        title: 'Defining Test of Faith',
        chapters: [
          { bookName: 'Genesis', chapter: 15 },
          { bookName: 'Genesis', chapter: 17 },
          { bookName: 'Genesis', chapter: 22 },
        ]
      },
      {
        title: 'Covenant & Commissioning',
        chapters: [
          { bookName: 'Genesis', chapter: 12 },
          { bookName: 'Genesis', chapter: 13 },
          { bookName: 'Genesis', chapter: 14 },
        ]
      },
      {
        title: 'Life of Faith',
        chapters: [
          { bookName: 'Genesis', chapter: 18 },
          { bookName: 'Genesis', chapter: 19 },
          { bookName: 'Genesis', chapter: 20 },
          { bookName: 'Genesis', chapter: 21 },
          { bookName: 'Genesis', chapter: 23 },
          { bookName: 'Genesis', chapter: 24 },
          { bookName: 'Genesis', chapter: 25 },
        ]
      },
      {
        title: 'Legacy & Later Remembrance',
        chapters: [
          { bookName: 'Joshua', chapter: 24 },
          { bookName: 'Nehemiah', chapter: 9 },
          { bookName: 'Psalms', chapter: 105 },
          { bookName: 'Isaiah', chapter: 51 },
          { bookName: 'Romans', chapter: 4 },
          { bookName: 'Galatians', chapter: 3 },
          { bookName: 'Hebrews', chapter: 11 },
          { bookName: 'James', chapter: 2 },
        ]
      }
    ]
  },
  
  Job: {
    iconKey: 'storm',
    accentColorKey: 'slate',
    hook: "Faith when answers don't come.",
    description: "Walk through Job's suffering, honest questions, and restored trust in God's wisdom and sovereignty.",
    sections: [
      {
        title: 'Formation & Setting',
        chapters: [
          { bookName: 'Job', chapter: 1 },
          { bookName: 'Job', chapter: 2 },
        ]
      },
      {
        title: 'Defining Trial',
        chapters: [
          { bookName: 'Job', chapter: 3 },
          { bookName: 'Job', chapter: 4 },
          { bookName: 'Job', chapter: 5 },
          { bookName: 'Job', chapter: 6 },
          { bookName: 'Job', chapter: 7 },
          { bookName: 'Job', chapter: 8 },
          { bookName: 'Job', chapter: 9 },
          { bookName: 'Job', chapter: 10 },
          { bookName: 'Job', chapter: 11 },
          { bookName: 'Job', chapter: 12 },
          { bookName: 'Job', chapter: 13 },
          { bookName: 'Job', chapter: 14 },
        ]
      },
      {
        title: 'Wrestling with God',
        chapters: [
          { bookName: 'Job', chapter: 15 },
          { bookName: 'Job', chapter: 16 },
          { bookName: 'Job', chapter: 17 },
          { bookName: 'Job', chapter: 18 },
          { bookName: 'Job', chapter: 19 },
          { bookName: 'Job', chapter: 20 },
          { bookName: 'Job', chapter: 21 },
          { bookName: 'Job', chapter: 22 },
          { bookName: 'Job', chapter: 23 },
          { bookName: 'Job', chapter: 24 },
          { bookName: 'Job', chapter: 25 },
          { bookName: 'Job', chapter: 26 },
          { bookName: 'Job', chapter: 27 },
          { bookName: 'Job', chapter: 28 },
          { bookName: 'Job', chapter: 29 },
          { bookName: 'Job', chapter: 30 },
          { bookName: 'Job', chapter: 31 },
        ]
      },
      {
        title: "God Speaks",
        chapters: [
          { bookName: 'Job', chapter: 32 },
          { bookName: 'Job', chapter: 33 },
          { bookName: 'Job', chapter: 34 },
          { bookName: 'Job', chapter: 35 },
          { bookName: 'Job', chapter: 36 },
          { bookName: 'Job', chapter: 37 },
          { bookName: 'Job', chapter: 38 },
          { bookName: 'Job', chapter: 39 },
          { bookName: 'Job', chapter: 40 },
          { bookName: 'Job', chapter: 41 },
        ]
      },
      {
        title: 'Restoration & Legacy',
        chapters: [
          { bookName: 'Job', chapter: 42 },
          { bookName: 'Ezekiel', chapter: 14 },
          { bookName: 'James', chapter: 5 },
        ]
      }
    ]
  },
  
  Joseph: {
    iconKey: 'coat',
    accentColorKey: 'emerald',
    hook: 'God was working, even in the pit.',
    description: "Trace Joseph's journey from betrayal to leadership as God uses hardship to accomplish His purposes.",
    sections: [
      {
        title: 'Formation & Family Context',
        chapters: [
          { bookName: 'Genesis', chapter: 37 },
        ]
      },
      {
        title: 'Defining Trials',
        chapters: [
          { bookName: 'Genesis', chapter: 39 },
          { bookName: 'Genesis', chapter: 40 },
        ]
      },
      {
        title: "God's Promotion",
        chapters: [
          { bookName: 'Genesis', chapter: 41 },
        ]
      },
      {
        title: "God's Purpose Revealed",
        chapters: [
          { bookName: 'Genesis', chapter: 42 },
          { bookName: 'Genesis', chapter: 43 },
          { bookName: 'Genesis', chapter: 44 },
          { bookName: 'Genesis', chapter: 45 },
          { bookName: 'Genesis', chapter: 46 },
          { bookName: 'Genesis', chapter: 47 },
          { bookName: 'Genesis', chapter: 48 },
          { bookName: 'Genesis', chapter: 49 },
          { bookName: 'Genesis', chapter: 50 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Psalms', chapter: 105 },
          { bookName: 'Acts', chapter: 7 },
        ]
      }
    ]
  },
  
  Moses: {
    iconKey: 'tablets',
    accentColorKey: 'purple',
    hook: 'Chosen by God. Tested by people.',
    description: "Explore Moses' life from reluctant shepherd to faithful servant leading God's people.",
    sections: [
      {
        title: 'Formation & Calling',
        chapters: [
          { bookName: 'Exodus', chapter: 1 },
          { bookName: 'Exodus', chapter: 2 },
          { bookName: 'Exodus', chapter: 3 },
          { bookName: 'Exodus', chapter: 4 },
          { bookName: 'Exodus', chapter: 5 },
          { bookName: 'Exodus', chapter: 6 },
        ]
      },
      {
        title: 'Defining Test',
        chapters: [
          { bookName: 'Exodus', chapter: 7 },
          { bookName: 'Exodus', chapter: 8 },
          { bookName: 'Exodus', chapter: 9 },
          { bookName: 'Exodus', chapter: 10 },
          { bookName: 'Exodus', chapter: 11 },
          { bookName: 'Exodus', chapter: 12 },
          { bookName: 'Exodus', chapter: 13 },
          { bookName: 'Exodus', chapter: 14 },
        ]
      },
      {
        title: 'Leadership Under Pressure',
        chapters: [
          { bookName: 'Exodus', chapter: 15 },
          { bookName: 'Exodus', chapter: 16 },
          { bookName: 'Exodus', chapter: 17 },
          { bookName: 'Exodus', chapter: 18 },
          { bookName: 'Exodus', chapter: 19 },
          { bookName: 'Exodus', chapter: 20 },
          { bookName: 'Exodus', chapter: 21 },
          { bookName: 'Exodus', chapter: 22 },
          { bookName: 'Exodus', chapter: 23 },
          { bookName: 'Exodus', chapter: 24 },
          { bookName: 'Exodus', chapter: 25 },
          { bookName: 'Exodus', chapter: 26 },
          { bookName: 'Exodus', chapter: 27 },
          { bookName: 'Exodus', chapter: 28 },
          { bookName: 'Exodus', chapter: 29 },
          { bookName: 'Exodus', chapter: 30 },
          { bookName: 'Exodus', chapter: 31 },
          { bookName: 'Exodus', chapter: 32 },
          { bookName: 'Exodus', chapter: 33 },
          { bookName: 'Exodus', chapter: 34 },
          { bookName: 'Numbers', chapter: 11 },
          { bookName: 'Numbers', chapter: 12 },
          { bookName: 'Numbers', chapter: 13 },
          { bookName: 'Numbers', chapter: 14 },
          { bookName: 'Numbers', chapter: 20 },
        ]
      },
      {
        title: 'Final Years & Instruction',
        chapters: [
          { bookName: 'Deuteronomy', chapter: 1 },
          { bookName: 'Deuteronomy', chapter: 2 },
          { bookName: 'Deuteronomy', chapter: 3 },
          { bookName: 'Deuteronomy', chapter: 4 },
          { bookName: 'Deuteronomy', chapter: 5 },
          { bookName: 'Deuteronomy', chapter: 6 },
          { bookName: 'Deuteronomy', chapter: 7 },
          { bookName: 'Deuteronomy', chapter: 8 },
          { bookName: 'Deuteronomy', chapter: 9 },
          { bookName: 'Deuteronomy', chapter: 10 },
          { bookName: 'Deuteronomy', chapter: 28 },
          { bookName: 'Deuteronomy', chapter: 29 },
          { bookName: 'Deuteronomy', chapter: 30 },
          { bookName: 'Deuteronomy', chapter: 31 },
          { bookName: 'Deuteronomy', chapter: 32 },
          { bookName: 'Deuteronomy', chapter: 33 },
          { bookName: 'Deuteronomy', chapter: 34 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Psalms', chapter: 90 },
          { bookName: 'Psalms', chapter: 105 },
          { bookName: 'Acts', chapter: 7 },
          { bookName: 'Hebrews', chapter: 11 },
          { bookName: 'Jude', chapter: 1 },
        ]
      }
    ]
  },
  
  Joshua: {
    iconKey: 'sword',
    accentColorKey: 'orange',
    hook: 'Strong, courageous, obedient.',
    description: "Follow Joshua from servant under Moses to faithful leader of Israel, emphasizing obedience to God's Word.",
    sections: [
      {
        title: 'Formation under Moses',
        chapters: [
          { bookName: 'Exodus', chapter: 17 },
          { bookName: 'Exodus', chapter: 24 },
          { bookName: 'Exodus', chapter: 32 },
          { bookName: 'Exodus', chapter: 33 },
        ]
      },
      {
        title: 'Defining Test of Faith',
        chapters: [
          { bookName: 'Numbers', chapter: 13 },
          { bookName: 'Numbers', chapter: 14 },
        ]
      },
      {
        title: 'Commissioning',
        chapters: [
          { bookName: 'Numbers', chapter: 27 },
          { bookName: 'Deuteronomy', chapter: 31 },
          { bookName: 'Deuteronomy', chapter: 34 },
          { bookName: 'Joshua', chapter: 1 },
        ]
      },
      {
        title: 'Leadership Narrative',
        chapters: [
          { bookName: 'Joshua', chapter: 2 },
          { bookName: 'Joshua', chapter: 3 },
          { bookName: 'Joshua', chapter: 4 },
          { bookName: 'Joshua', chapter: 5 },
          { bookName: 'Joshua', chapter: 6 },
          { bookName: 'Joshua', chapter: 7 },
          { bookName: 'Joshua', chapter: 8 },
          { bookName: 'Joshua', chapter: 9 },
          { bookName: 'Joshua', chapter: 10 },
          { bookName: 'Joshua', chapter: 11 },
          { bookName: 'Joshua', chapter: 12 },
          { bookName: 'Joshua', chapter: 13 },
          { bookName: 'Joshua', chapter: 14 },
          { bookName: 'Joshua', chapter: 15 },
          { bookName: 'Joshua', chapter: 16 },
          { bookName: 'Joshua', chapter: 17 },
          { bookName: 'Joshua', chapter: 18 },
          { bookName: 'Joshua', chapter: 19 },
          { bookName: 'Joshua', chapter: 20 },
          { bookName: 'Joshua', chapter: 21 },
          { bookName: 'Joshua', chapter: 22 },
          { bookName: 'Joshua', chapter: 23 },
          { bookName: 'Joshua', chapter: 24 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Judges', chapter: 2 },
          { bookName: 'Nehemiah', chapter: 9 },
          { bookName: 'Psalms', chapter: 44 },
          { bookName: 'Psalms', chapter: 105 },
        ]
      }
    ]
  },
  
  David: {
    iconKey: 'harp',
    accentColorKey: 'cyan',
    hook: 'A heart for God—even when he failed.',
    description: "Study the rise, reign, repentance, and legacy of Israel's greatest king.",
    sections: [
      {
        title: 'Formation & Calling',
        chapters: [
          { bookName: '1 Samuel', chapter: 16 },
          { bookName: '1 Samuel', chapter: 17 },
        ]
      },
      {
        title: 'Defining Trials',
        chapters: [
          { bookName: '1 Samuel', chapter: 18 },
          { bookName: '1 Samuel', chapter: 19 },
          { bookName: '1 Samuel', chapter: 20 },
          { bookName: '1 Samuel', chapter: 21 },
          { bookName: '1 Samuel', chapter: 22 },
          { bookName: '1 Samuel', chapter: 23 },
          { bookName: '1 Samuel', chapter: 24 },
          { bookName: '1 Samuel', chapter: 25 },
          { bookName: '1 Samuel', chapter: 26 },
          { bookName: '1 Samuel', chapter: 27 },
          { bookName: '1 Samuel', chapter: 28 },
          { bookName: '1 Samuel', chapter: 29 },
          { bookName: '1 Samuel', chapter: 30 },
          { bookName: '1 Samuel', chapter: 31 },
        ]
      },
      {
        title: 'Kingship Established',
        chapters: [
          { bookName: '2 Samuel', chapter: 1 },
          { bookName: '2 Samuel', chapter: 2 },
          { bookName: '2 Samuel', chapter: 3 },
          { bookName: '2 Samuel', chapter: 4 },
          { bookName: '2 Samuel', chapter: 5 },
          { bookName: '2 Samuel', chapter: 6 },
          { bookName: '2 Samuel', chapter: 7 },
          { bookName: '2 Samuel', chapter: 8 },
          { bookName: '2 Samuel', chapter: 9 },
          { bookName: '2 Samuel', chapter: 10 },
        ]
      },
      {
        title: 'Leadership & Failure',
        chapters: [
          { bookName: '2 Samuel', chapter: 11 },
          { bookName: '2 Samuel', chapter: 12 },
          { bookName: '2 Samuel', chapter: 13 },
          { bookName: '2 Samuel', chapter: 14 },
          { bookName: '2 Samuel', chapter: 15 },
          { bookName: '2 Samuel', chapter: 16 },
          { bookName: '2 Samuel', chapter: 17 },
          { bookName: '2 Samuel', chapter: 18 },
          { bookName: '2 Samuel', chapter: 19 },
          { bookName: '2 Samuel', chapter: 20 },
          { bookName: '2 Samuel', chapter: 21 },
          { bookName: '2 Samuel', chapter: 22 },
          { bookName: '2 Samuel', chapter: 23 },
          { bookName: '2 Samuel', chapter: 24 },
          { bookName: '1 Kings', chapter: 1 },
          { bookName: '1 Kings', chapter: 2 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Psalms', chapter: 3 },
          { bookName: 'Psalms', chapter: 18 },
          { bookName: 'Psalms', chapter: 23 },
          { bookName: 'Psalms', chapter: 51 },
          { bookName: 'Psalms', chapter: 103 },
          { bookName: 'Acts', chapter: 13 },
          { bookName: 'Romans', chapter: 1 },
        ]
      }
    ]
  },
  
  Elijah: {
    iconKey: 'fire',
    accentColorKey: 'red',
    hook: 'Faithful when standing alone.',
    description: "Walk with Elijah through bold faith, deep discouragement, and renewed strength from God.",
    sections: [
      {
        title: 'Sudden Calling',
        chapters: [
          { bookName: '1 Kings', chapter: 17 },
        ]
      },
      {
        title: 'Defining Confrontation',
        chapters: [
          { bookName: '1 Kings', chapter: 18 },
        ]
      },
      {
        title: 'Discouragement & Renewal',
        chapters: [
          { bookName: '1 Kings', chapter: 19 },
        ]
      },
      {
        title: 'Final Ministry & Transition',
        chapters: [
          { bookName: '1 Kings', chapter: 20 },
          { bookName: '1 Kings', chapter: 21 },
          { bookName: '1 Kings', chapter: 22 },
          { bookName: '2 Kings', chapter: 1 },
          { bookName: '2 Kings', chapter: 2 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Malachi', chapter: 4 },
          { bookName: 'Matthew', chapter: 17 },
          { bookName: 'Luke', chapter: 4 },
          { bookName: 'James', chapter: 5 },
        ]
      }
    ]
  },
  
  Daniel: {
    iconKey: 'lion',
    accentColorKey: 'amber',
    hook: 'Faithful in a hostile world.',
    description: "Follow Daniel's unwavering faith and trust in God's sovereignty while living in exile.",
    sections: [
      {
        title: 'Formation in Captivity',
        chapters: [
          { bookName: 'Daniel', chapter: 1 },
        ]
      },
      {
        title: 'Defining Stands',
        chapters: [
          { bookName: 'Daniel', chapter: 2 },
          { bookName: 'Daniel', chapter: 3 },
          { bookName: 'Daniel', chapter: 6 },
        ]
      },
      {
        title: "God's Revelation",
        chapters: [
          { bookName: 'Daniel', chapter: 4 },
          { bookName: 'Daniel', chapter: 5 },
          { bookName: 'Daniel', chapter: 7 },
          { bookName: 'Daniel', chapter: 8 },
          { bookName: 'Daniel', chapter: 9 },
        ]
      },
      {
        title: 'Endurance in Leadership',
        chapters: [
          { bookName: 'Daniel', chapter: 10 },
          { bookName: 'Daniel', chapter: 11 },
          { bookName: 'Daniel', chapter: 12 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Ezekiel', chapter: 14 },
          { bookName: 'Matthew', chapter: 24 },
        ]
      }
    ]
  },
  
  Peter: {
    iconKey: 'keys',
    accentColorKey: 'indigo',
    hook: 'Restored by grace, strengthened for service.',
    description: "Trace Peter's transformation from fearful disciple to faithful shepherd of the early church.",
    sections: [
      {
        title: 'Formation as a Disciple',
        chapters: [
          { bookName: 'Matthew', chapter: 4 },
          { bookName: 'Luke', chapter: 5 },
          { bookName: 'John', chapter: 1 },
        ]
      },
      {
        title: 'Defining Failure',
        chapters: [
          { bookName: 'Matthew', chapter: 14 },
          { bookName: 'Matthew', chapter: 16 },
          { bookName: 'Matthew', chapter: 26 },
          { bookName: 'Luke', chapter: 22 },
        ]
      },
      {
        title: 'Restoration & Commissioning',
        chapters: [
          { bookName: 'John', chapter: 21 },
        ]
      },
      {
        title: 'Leadership in the Church',
        chapters: [
          { bookName: 'Acts', chapter: 1 },
          { bookName: 'Acts', chapter: 2 },
          { bookName: 'Acts', chapter: 3 },
          { bookName: 'Acts', chapter: 4 },
          { bookName: 'Acts', chapter: 5 },
          { bookName: 'Acts', chapter: 10 },
          { bookName: 'Acts', chapter: 11 },
          { bookName: 'Acts', chapter: 12 },
        ]
      },
      {
        title: 'Legacy & Teaching',
        chapters: [
          { bookName: '1 Peter', chapter: 1 },
          { bookName: '1 Peter', chapter: 2 },
          { bookName: '1 Peter', chapter: 3 },
          { bookName: '1 Peter', chapter: 4 },
          { bookName: '1 Peter', chapter: 5 },
          { bookName: '2 Peter', chapter: 1 },
          { bookName: '2 Peter', chapter: 2 },
          { bookName: '2 Peter', chapter: 3 },
          { bookName: 'Galatians', chapter: 2 },
        ]
      }
    ]
  },
  
  Paul: {
    iconKey: 'scroll',
    accentColorKey: 'rose',
    hook: 'Saved by grace. Sent with purpose.',
    description: "Journey through Paul's conversion, missionary ministry, and final testimony of faith.",
    sections: [
      {
        title: 'Formation & Opposition',
        chapters: [
          { bookName: 'Acts', chapter: 7 },
          { bookName: 'Acts', chapter: 8 },
        ]
      },
      {
        title: 'Defining Conversion',
        chapters: [
          { bookName: 'Acts', chapter: 9 },
        ]
      },
      {
        title: 'Calling Confirmed',
        chapters: [
          { bookName: 'Acts', chapter: 13 },
          { bookName: 'Acts', chapter: 26 },
        ]
      },
      {
        title: 'Missionary Leadership',
        chapters: [
          { bookName: 'Acts', chapter: 14 },
          { bookName: 'Acts', chapter: 15 },
          { bookName: 'Acts', chapter: 16 },
          { bookName: 'Acts', chapter: 17 },
          { bookName: 'Acts', chapter: 18 },
          { bookName: 'Acts', chapter: 19 },
          { bookName: 'Acts', chapter: 20 },
          { bookName: 'Acts', chapter: 21 },
          { bookName: 'Acts', chapter: 22 },
          { bookName: 'Acts', chapter: 23 },
          { bookName: 'Acts', chapter: 24 },
          { bookName: 'Acts', chapter: 25 },
          { bookName: 'Acts', chapter: 27 },
          { bookName: 'Acts', chapter: 28 },
          { bookName: 'Romans', chapter: 1 },
          { bookName: 'Romans', chapter: 2 },
          { bookName: 'Romans', chapter: 3 },
          { bookName: 'Romans', chapter: 4 },
          { bookName: 'Romans', chapter: 5 },
          { bookName: 'Romans', chapter: 6 },
          { bookName: 'Romans', chapter: 7 },
          { bookName: 'Romans', chapter: 8 },
          { bookName: 'Romans', chapter: 9 },
          { bookName: 'Romans', chapter: 10 },
          { bookName: 'Romans', chapter: 11 },
          { bookName: 'Romans', chapter: 12 },
          { bookName: 'Romans', chapter: 13 },
          { bookName: 'Romans', chapter: 14 },
          { bookName: 'Romans', chapter: 15 },
          { bookName: 'Romans', chapter: 16 },
        ]
      },
      {
        title: 'Legacy & Final Testimony',
        chapters: [
          { bookName: '1 Timothy', chapter: 1 },
          { bookName: '1 Timothy', chapter: 2 },
          { bookName: '1 Timothy', chapter: 3 },
          { bookName: '1 Timothy', chapter: 4 },
          { bookName: '1 Timothy', chapter: 5 },
          { bookName: '1 Timothy', chapter: 6 },
          { bookName: '2 Timothy', chapter: 1 },
          { bookName: '2 Timothy', chapter: 2 },
          { bookName: '2 Timothy', chapter: 3 },
          { bookName: '2 Timothy', chapter: 4 },
          { bookName: 'Titus', chapter: 1 },
          { bookName: 'Titus', chapter: 2 },
          { bookName: 'Titus', chapter: 3 },
          { bookName: 'Philemon', chapter: 1 },
        ]
      }
    ]
  },

  Esther: {
    iconKey: 'crown',
    accentColorKey: 'rose',
    hook: 'Courage and faith under unseen providence.',
    description: "Trace God's hidden hand through Esther's courage, obedience, and sacrifice. This study explores divine providence, faith under pressure, and God's preservation of His people.",
    sections: [
      {
        title: 'Captivity & Context',
        chapters: [
          { bookName: '2 Kings', chapter: 24 },
          { bookName: '2 Kings', chapter: 25 },
          { bookName: 'Ezra', chapter: 1 },
        ]
      },
      {
        title: 'Queen & Hidden Identity',
        chapters: [
          { bookName: 'Esther', chapter: 1 },
          { bookName: 'Esther', chapter: 2 },
          { bookName: 'Esther', chapter: 3 },
        ]
      },
      {
        title: 'Crisis of Faith',
        chapters: [
          { bookName: 'Esther', chapter: 4 },
          { bookName: 'Esther', chapter: 5 },
          { bookName: 'Esther', chapter: 6 },
        ]
      },
      {
        title: 'Courage & Deliverance',
        chapters: [
          { bookName: 'Esther', chapter: 7 },
          { bookName: 'Esther', chapter: 8 },
          { bookName: 'Esther', chapter: 9 },
          { bookName: 'Esther', chapter: 10 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Nehemiah', chapter: 9 },
          { bookName: 'Psalm', chapter: 124 },
        ]
      }
    ]
  },

  Ruth: {
    iconKey: 'wheat',
    accentColorKey: 'amber',
    hook: 'Faithfulness in obscurity, redemption through obedience.',
    description: "Walk through Ruth's quiet faith, God's unseen providence, and the redemptive line leading to Christ. This study highlights loyalty, humility, and God's sovereign work through ordinary faithfulness.",
    sections: [
      {
        title: 'Loss & Beginning',
        chapters: [
          { bookName: 'Judges', chapter: 21 },
          { bookName: 'Ruth', chapter: 1 },
        ]
      },
      {
        title: 'Faithfulness in the Harvest',
        chapters: [
          { bookName: 'Ruth', chapter: 2 },
        ]
      },
      {
        title: "Seeking Redemption",
        chapters: [
          { bookName: 'Ruth', chapter: 3 },
        ]
      },
      {
        title: 'Restoration & Belonging',
        chapters: [
          { bookName: 'Ruth', chapter: 4 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Matthew', chapter: 1 },
          { bookName: '1 Samuel', chapter: 16 },
          { bookName: 'Luke', chapter: 3 },
        ]
      }
    ]
  },

  Mary: {
    iconKey: 'heart',
    accentColorKey: 'cyan',
    hook: 'Be it unto me according to thy word.',
    description: "Study the life of Mary as a humble servant chosen by God for an extraordinary purpose. This plan emphasizes submission, faith, worship, and trust in God's promises.",
    sections: [
      {
        title: 'Formation & Calling',
        chapters: [
          { bookName: 'Luke', chapter: 1 },
        ]
      },
      {
        title: 'Defining Act of Faith',
        chapters: [
          { bookName: 'Luke', chapter: 2 },
          { bookName: 'Matthew', chapter: 1 },
          { bookName: 'Matthew', chapter: 2 },
        ]
      },
      {
        title: 'Treasuring God\'s Work',
        chapters: [
          { bookName: 'John', chapter: 2 },
        ]
      },
      {
        title: "Witnessing Christ's Life",
        chapters: [
          { bookName: 'John', chapter: 19 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Acts', chapter: 1 },
        ]
      }
    ]
  },

  Deborah: {
    iconKey: 'torch',
    accentColorKey: 'indigo',
    hook: 'Faithful leadership in a compromised generation.',
    description: "Study Deborah's role as judge and prophetess during Israel's darkest days. This plan traces God's sovereign leadership through obedience, courage, and trust in His word when others failed to lead.",
    sections: [
      {
        title: 'The Context of Compromise',
        chapters: [
          { bookName: 'Judges', chapter: 1 },
          { bookName: 'Judges', chapter: 2 },
          { bookName: 'Judges', chapter: 3 },
        ]
      },
      {
        title: 'Deborah: Judge & Prophetess',
        chapters: [
          { bookName: 'Judges', chapter: 4 },
          { bookName: 'Judges', chapter: 5 },
        ]
      },
      {
        title: "God's People Restored",
        chapters: [
          { bookName: 'Judges', chapter: 6 },
          { bookName: 'Judges', chapter: 7 },
          { bookName: 'Judges', chapter: 8 },
        ]
      },
      {
        title: "The Pattern Repeats",
        chapters: [
          { bookName: 'Judges', chapter: 17 },
          { bookName: 'Judges', chapter: 21 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Hebrews', chapter: 11 },
        ]
      }
    ]
  },

  Hannah: {
    iconKey: 'prayer',
    accentColorKey: 'cyan',
    hook: 'A surrendered heart that shaped a nation.',
    description: "Study Hannah's prayerful dependence on God and how quiet faith produced lasting spiritual impact. This plan traces prayer, surrender, and God's purposes beyond personal pain.",
    sections: [
      {
        title: 'Formation & Heartache',
        chapters: [
          { bookName: 'Judges', chapter: 21 },
          { bookName: '1 Samuel', chapter: 1 },
        ]
      },
      {
        title: 'Prayer & Surrender',
        chapters: [
          { bookName: '1 Samuel', chapter: 2 },
        ]
      },
      {
        title: "Samuel: God's Answer",
        chapters: [
          { bookName: '1 Samuel', chapter: 3 },
          { bookName: '1 Samuel', chapter: 7 },
        ]
      },
      {
        title: 'Guidance & Leadership',
        chapters: [
          { bookName: '1 Samuel', chapter: 8 },
          { bookName: '1 Samuel', chapter: 12 },
        ]
      },
      {
        title: 'Legacy & Remembrance',
        chapters: [
          { bookName: 'Luke', chapter: 1 },
        ]
      }
    ]
  },

  ChronologicalOT: {
    iconKey: 'scroll',
    accentColorKey: 'amber',
    hook: 'The Old Testament story as it unfolded.',
    description: "Read the Old Testament as one unfolding story. This guided plan walks through the Scriptures in historical order, helping you see how God's work unfolds across people, nations, and covenants.",
    sections: [
      {
        title: 'Creation & The Patriarchs',
        chapters: [
          { bookName: 'Genesis', chapter: 1 },
          { bookName: 'Genesis', chapter: 2 },
          { bookName: 'Genesis', chapter: 3 },
          { bookName: 'Genesis', chapter: 4 },
          { bookName: 'Genesis', chapter: 5 },
          { bookName: 'Genesis', chapter: 6 },
          { bookName: 'Genesis', chapter: 7 },
          { bookName: 'Genesis', chapter: 8 },
          { bookName: 'Genesis', chapter: 9 },
          { bookName: 'Genesis', chapter: 10 },
          { bookName: 'Genesis', chapter: 11 },
          { bookName: 'Job', chapter: 1 },
          { bookName: 'Job', chapter: 2 },
          { bookName: 'Job', chapter: 3 },
          { bookName: 'Job', chapter: 4 },
          { bookName: 'Job', chapter: 5 },
          { bookName: 'Job', chapter: 6 },
          { bookName: 'Job', chapter: 7 },
          { bookName: 'Job', chapter: 8 },
          { bookName: 'Job', chapter: 9 },
          { bookName: 'Job', chapter: 10 },
          { bookName: 'Job', chapter: 11 },
          { bookName: 'Job', chapter: 12 },
          { bookName: 'Job', chapter: 13 },
          { bookName: 'Job', chapter: 14 },
          { bookName: 'Job', chapter: 15 },
          { bookName: 'Job', chapter: 16 },
          { bookName: 'Job', chapter: 17 },
          { bookName: 'Job', chapter: 18 },
          { bookName: 'Job', chapter: 19 },
          { bookName: 'Job', chapter: 20 },
          { bookName: 'Job', chapter: 21 },
          { bookName: 'Job', chapter: 22 },
          { bookName: 'Job', chapter: 23 },
          { bookName: 'Job', chapter: 24 },
          { bookName: 'Job', chapter: 25 },
          { bookName: 'Job', chapter: 26 },
          { bookName: 'Job', chapter: 27 },
          { bookName: 'Job', chapter: 28 },
          { bookName: 'Job', chapter: 29 },
          { bookName: 'Job', chapter: 30 },
          { bookName: 'Job', chapter: 31 },
          { bookName: 'Job', chapter: 32 },
          { bookName: 'Job', chapter: 33 },
          { bookName: 'Job', chapter: 34 },
          { bookName: 'Job', chapter: 35 },
          { bookName: 'Job', chapter: 36 },
          { bookName: 'Job', chapter: 37 },
          { bookName: 'Job', chapter: 38 },
          { bookName: 'Job', chapter: 39 },
          { bookName: 'Job', chapter: 40 },
          { bookName: 'Job', chapter: 41 },
          { bookName: 'Job', chapter: 42 },
          { bookName: 'Genesis', chapter: 12 },
          { bookName: 'Genesis', chapter: 13 },
          { bookName: 'Genesis', chapter: 14 },
          { bookName: 'Genesis', chapter: 15 },
          { bookName: 'Genesis', chapter: 16 },
          { bookName: 'Genesis', chapter: 17 },
          { bookName: 'Genesis', chapter: 18 },
          { bookName: 'Genesis', chapter: 19 },
          { bookName: 'Genesis', chapter: 20 },
          { bookName: 'Genesis', chapter: 21 },
          { bookName: 'Genesis', chapter: 22 },
          { bookName: 'Genesis', chapter: 23 },
          { bookName: 'Genesis', chapter: 24 },
          { bookName: 'Genesis', chapter: 25 },
          { bookName: 'Genesis', chapter: 26 },
          { bookName: 'Genesis', chapter: 27 },
          { bookName: 'Genesis', chapter: 28 },
          { bookName: 'Genesis', chapter: 29 },
          { bookName: 'Genesis', chapter: 30 },
          { bookName: 'Genesis', chapter: 31 },
          { bookName: 'Genesis', chapter: 32 },
          { bookName: 'Genesis', chapter: 33 },
          { bookName: 'Genesis', chapter: 34 },
          { bookName: 'Genesis', chapter: 35 },
          { bookName: 'Genesis', chapter: 36 },
          { bookName: 'Genesis', chapter: 37 },
          { bookName: 'Genesis', chapter: 38 },
          { bookName: 'Genesis', chapter: 39 },
          { bookName: 'Genesis', chapter: 40 },
          { bookName: 'Genesis', chapter: 41 },
          { bookName: 'Genesis', chapter: 42 },
          { bookName: 'Genesis', chapter: 43 },
          { bookName: 'Genesis', chapter: 44 },
          { bookName: 'Genesis', chapter: 45 },
          { bookName: 'Genesis', chapter: 46 },
          { bookName: 'Genesis', chapter: 47 },
          { bookName: 'Genesis', chapter: 48 },
          { bookName: 'Genesis', chapter: 49 },
          { bookName: 'Genesis', chapter: 50 },
        ]
      },
      {
        title: 'Exodus & The Law',
        chapters: [
          { bookName: 'Exodus', chapter: 1 },
          { bookName: 'Exodus', chapter: 2 },
          { bookName: 'Exodus', chapter: 3 },
          { bookName: 'Exodus', chapter: 4 },
          { bookName: 'Exodus', chapter: 5 },
          { bookName: 'Exodus', chapter: 6 },
          { bookName: 'Exodus', chapter: 7 },
          { bookName: 'Exodus', chapter: 8 },
          { bookName: 'Exodus', chapter: 9 },
          { bookName: 'Exodus', chapter: 10 },
          { bookName: 'Exodus', chapter: 11 },
          { bookName: 'Exodus', chapter: 12 },
          { bookName: 'Exodus', chapter: 13 },
          { bookName: 'Exodus', chapter: 14 },
          { bookName: 'Exodus', chapter: 15 },
          { bookName: 'Exodus', chapter: 16 },
          { bookName: 'Exodus', chapter: 17 },
          { bookName: 'Exodus', chapter: 18 },
          { bookName: 'Exodus', chapter: 19 },
          { bookName: 'Exodus', chapter: 20 },
          { bookName: 'Exodus', chapter: 21 },
          { bookName: 'Exodus', chapter: 22 },
          { bookName: 'Exodus', chapter: 23 },
          { bookName: 'Exodus', chapter: 24 },
          { bookName: 'Exodus', chapter: 25 },
          { bookName: 'Exodus', chapter: 26 },
          { bookName: 'Exodus', chapter: 27 },
          { bookName: 'Exodus', chapter: 28 },
          { bookName: 'Exodus', chapter: 29 },
          { bookName: 'Exodus', chapter: 30 },
          { bookName: 'Exodus', chapter: 31 },
          { bookName: 'Exodus', chapter: 32 },
          { bookName: 'Exodus', chapter: 33 },
          { bookName: 'Exodus', chapter: 34 },
          { bookName: 'Exodus', chapter: 35 },
          { bookName: 'Exodus', chapter: 36 },
          { bookName: 'Exodus', chapter: 37 },
          { bookName: 'Exodus', chapter: 38 },
          { bookName: 'Exodus', chapter: 39 },
          { bookName: 'Exodus', chapter: 40 },
          { bookName: 'Leviticus', chapter: 1 },
          { bookName: 'Leviticus', chapter: 2 },
          { bookName: 'Leviticus', chapter: 3 },
          { bookName: 'Leviticus', chapter: 4 },
          { bookName: 'Leviticus', chapter: 5 },
          { bookName: 'Leviticus', chapter: 6 },
          { bookName: 'Leviticus', chapter: 7 },
          { bookName: 'Leviticus', chapter: 8 },
          { bookName: 'Leviticus', chapter: 9 },
          { bookName: 'Leviticus', chapter: 10 },
          { bookName: 'Leviticus', chapter: 11 },
          { bookName: 'Leviticus', chapter: 12 },
          { bookName: 'Leviticus', chapter: 13 },
          { bookName: 'Leviticus', chapter: 14 },
          { bookName: 'Leviticus', chapter: 15 },
          { bookName: 'Leviticus', chapter: 16 },
          { bookName: 'Leviticus', chapter: 17 },
          { bookName: 'Leviticus', chapter: 18 },
          { bookName: 'Leviticus', chapter: 19 },
          { bookName: 'Leviticus', chapter: 20 },
          { bookName: 'Leviticus', chapter: 21 },
          { bookName: 'Leviticus', chapter: 22 },
          { bookName: 'Leviticus', chapter: 23 },
          { bookName: 'Leviticus', chapter: 24 },
          { bookName: 'Leviticus', chapter: 25 },
          { bookName: 'Leviticus', chapter: 26 },
          { bookName: 'Leviticus', chapter: 27 },
          { bookName: 'Numbers', chapter: 1 },
          { bookName: 'Numbers', chapter: 2 },
          { bookName: 'Numbers', chapter: 3 },
          { bookName: 'Numbers', chapter: 4 },
          { bookName: 'Numbers', chapter: 5 },
          { bookName: 'Numbers', chapter: 6 },
          { bookName: 'Numbers', chapter: 7 },
          { bookName: 'Numbers', chapter: 8 },
          { bookName: 'Numbers', chapter: 9 },
          { bookName: 'Numbers', chapter: 10 },
          { bookName: 'Numbers', chapter: 11 },
          { bookName: 'Numbers', chapter: 12 },
          { bookName: 'Numbers', chapter: 13 },
          { bookName: 'Numbers', chapter: 14 },
          { bookName: 'Numbers', chapter: 15 },
          { bookName: 'Numbers', chapter: 16 },
          { bookName: 'Numbers', chapter: 17 },
          { bookName: 'Numbers', chapter: 18 },
          { bookName: 'Numbers', chapter: 19 },
          { bookName: 'Numbers', chapter: 20 },
          { bookName: 'Numbers', chapter: 21 },
          { bookName: 'Numbers', chapter: 22 },
          { bookName: 'Numbers', chapter: 23 },
          { bookName: 'Numbers', chapter: 24 },
          { bookName: 'Numbers', chapter: 25 },
          { bookName: 'Numbers', chapter: 26 },
          { bookName: 'Numbers', chapter: 27 },
          { bookName: 'Numbers', chapter: 28 },
          { bookName: 'Numbers', chapter: 29 },
          { bookName: 'Numbers', chapter: 30 },
          { bookName: 'Numbers', chapter: 31 },
          { bookName: 'Numbers', chapter: 32 },
          { bookName: 'Numbers', chapter: 33 },
          { bookName: 'Numbers', chapter: 34 },
          { bookName: 'Numbers', chapter: 35 },
          { bookName: 'Numbers', chapter: 36 },
          { bookName: 'Psalms', chapter: 90 },
          { bookName: 'Deuteronomy', chapter: 1 },
          { bookName: 'Deuteronomy', chapter: 2 },
          { bookName: 'Deuteronomy', chapter: 3 },
          { bookName: 'Deuteronomy', chapter: 4 },
          { bookName: 'Deuteronomy', chapter: 5 },
          { bookName: 'Deuteronomy', chapter: 6 },
          { bookName: 'Deuteronomy', chapter: 7 },
          { bookName: 'Deuteronomy', chapter: 8 },
          { bookName: 'Deuteronomy', chapter: 9 },
          { bookName: 'Deuteronomy', chapter: 10 },
          { bookName: 'Deuteronomy', chapter: 11 },
          { bookName: 'Deuteronomy', chapter: 12 },
          { bookName: 'Deuteronomy', chapter: 13 },
          { bookName: 'Deuteronomy', chapter: 14 },
          { bookName: 'Deuteronomy', chapter: 15 },
          { bookName: 'Deuteronomy', chapter: 16 },
          { bookName: 'Deuteronomy', chapter: 17 },
          { bookName: 'Deuteronomy', chapter: 18 },
          { bookName: 'Deuteronomy', chapter: 19 },
          { bookName: 'Deuteronomy', chapter: 20 },
          { bookName: 'Deuteronomy', chapter: 21 },
          { bookName: 'Deuteronomy', chapter: 22 },
          { bookName: 'Deuteronomy', chapter: 23 },
          { bookName: 'Deuteronomy', chapter: 24 },
          { bookName: 'Deuteronomy', chapter: 25 },
          { bookName: 'Deuteronomy', chapter: 26 },
          { bookName: 'Deuteronomy', chapter: 27 },
          { bookName: 'Deuteronomy', chapter: 28 },
          { bookName: 'Deuteronomy', chapter: 29 },
          { bookName: 'Deuteronomy', chapter: 30 },
          { bookName: 'Deuteronomy', chapter: 31 },
          { bookName: 'Deuteronomy', chapter: 32 },
          { bookName: 'Deuteronomy', chapter: 33 },
          { bookName: 'Deuteronomy', chapter: 34 },
        ]
      },
      {
        title: 'Conquest & Judges',
        chapters: [
          { bookName: 'Joshua', chapter: 1 },
          { bookName: 'Joshua', chapter: 2 },
          { bookName: 'Joshua', chapter: 3 },
          { bookName: 'Joshua', chapter: 4 },
          { bookName: 'Joshua', chapter: 5 },
          { bookName: 'Joshua', chapter: 6 },
          { bookName: 'Joshua', chapter: 7 },
          { bookName: 'Joshua', chapter: 8 },
          { bookName: 'Joshua', chapter: 9 },
          { bookName: 'Joshua', chapter: 10 },
          { bookName: 'Joshua', chapter: 11 },
          { bookName: 'Joshua', chapter: 12 },
          { bookName: 'Joshua', chapter: 13 },
          { bookName: 'Joshua', chapter: 14 },
          { bookName: 'Joshua', chapter: 15 },
          { bookName: 'Joshua', chapter: 16 },
          { bookName: 'Joshua', chapter: 17 },
          { bookName: 'Joshua', chapter: 18 },
          { bookName: 'Joshua', chapter: 19 },
          { bookName: 'Joshua', chapter: 20 },
          { bookName: 'Joshua', chapter: 21 },
          { bookName: 'Joshua', chapter: 22 },
          { bookName: 'Joshua', chapter: 23 },
          { bookName: 'Joshua', chapter: 24 },
          { bookName: 'Judges', chapter: 1 },
          { bookName: 'Judges', chapter: 2 },
          { bookName: 'Judges', chapter: 3 },
          { bookName: 'Judges', chapter: 4 },
          { bookName: 'Judges', chapter: 5 },
          { bookName: 'Judges', chapter: 6 },
          { bookName: 'Judges', chapter: 7 },
          { bookName: 'Judges', chapter: 8 },
          { bookName: 'Judges', chapter: 9 },
          { bookName: 'Judges', chapter: 10 },
          { bookName: 'Judges', chapter: 11 },
          { bookName: 'Judges', chapter: 12 },
          { bookName: 'Judges', chapter: 13 },
          { bookName: 'Judges', chapter: 14 },
          { bookName: 'Judges', chapter: 15 },
          { bookName: 'Judges', chapter: 16 },
          { bookName: 'Judges', chapter: 17 },
          { bookName: 'Judges', chapter: 18 },
          { bookName: 'Judges', chapter: 19 },
          { bookName: 'Judges', chapter: 20 },
          { bookName: 'Judges', chapter: 21 },
          { bookName: 'Ruth', chapter: 1 },
          { bookName: 'Ruth', chapter: 2 },
          { bookName: 'Ruth', chapter: 3 },
          { bookName: 'Ruth', chapter: 4 },
        ]
      },
      {
        title: 'United Kingdom',
        chapters: [
          { bookName: '1 Samuel', chapter: 1 },
          { bookName: '1 Samuel', chapter: 2 },
          { bookName: '1 Samuel', chapter: 3 },
          { bookName: '1 Samuel', chapter: 4 },
          { bookName: '1 Samuel', chapter: 5 },
          { bookName: '1 Samuel', chapter: 6 },
          { bookName: '1 Samuel', chapter: 7 },
          { bookName: '1 Samuel', chapter: 8 },
          { bookName: '1 Samuel', chapter: 9 },
          { bookName: '1 Samuel', chapter: 10 },
          { bookName: '1 Samuel', chapter: 11 },
          { bookName: '1 Samuel', chapter: 12 },
          { bookName: '1 Samuel', chapter: 13 },
          { bookName: '1 Samuel', chapter: 14 },
          { bookName: '1 Samuel', chapter: 15 },
          { bookName: '1 Samuel', chapter: 16 },
          { bookName: '1 Samuel', chapter: 17 },
          { bookName: '1 Samuel', chapter: 18 },
          { bookName: '1 Samuel', chapter: 19 },
          { bookName: '1 Samuel', chapter: 20 },
          { bookName: '1 Samuel', chapter: 21 },
          { bookName: '1 Samuel', chapter: 22 },
          { bookName: '1 Samuel', chapter: 23 },
          { bookName: '1 Samuel', chapter: 24 },
          { bookName: '1 Samuel', chapter: 25 },
          { bookName: '1 Samuel', chapter: 26 },
          { bookName: '1 Samuel', chapter: 27 },
          { bookName: '1 Samuel', chapter: 28 },
          { bookName: '1 Samuel', chapter: 29 },
          { bookName: '1 Samuel', chapter: 30 },
          { bookName: '1 Samuel', chapter: 31 },
          { bookName: 'Psalms', chapter: 7 },
          { bookName: 'Psalms', chapter: 34 },
          { bookName: 'Psalms', chapter: 52 },
          { bookName: 'Psalms', chapter: 54 },
          { bookName: 'Psalms', chapter: 56 },
          { bookName: 'Psalms', chapter: 57 },
          { bookName: 'Psalms', chapter: 59 },
          { bookName: 'Psalms', chapter: 142 },
          { bookName: '2 Samuel', chapter: 1 },
          { bookName: '2 Samuel', chapter: 2 },
          { bookName: '2 Samuel', chapter: 3 },
          { bookName: '2 Samuel', chapter: 4 },
          { bookName: '2 Samuel', chapter: 5 },
          { bookName: '2 Samuel', chapter: 6 },
          { bookName: '2 Samuel', chapter: 7 },
          { bookName: '2 Samuel', chapter: 8 },
          { bookName: '2 Samuel', chapter: 9 },
          { bookName: '2 Samuel', chapter: 10 },
          { bookName: '2 Samuel', chapter: 11 },
          { bookName: '2 Samuel', chapter: 12 },
          { bookName: '2 Samuel', chapter: 13 },
          { bookName: '2 Samuel', chapter: 14 },
          { bookName: '2 Samuel', chapter: 15 },
          { bookName: '2 Samuel', chapter: 16 },
          { bookName: '2 Samuel', chapter: 17 },
          { bookName: '2 Samuel', chapter: 18 },
          { bookName: '2 Samuel', chapter: 19 },
          { bookName: '2 Samuel', chapter: 20 },
          { bookName: '2 Samuel', chapter: 21 },
          { bookName: '2 Samuel', chapter: 22 },
          { bookName: '2 Samuel', chapter: 23 },
          { bookName: '2 Samuel', chapter: 24 },
          { bookName: 'Psalms', chapter: 2 },
          { bookName: 'Psalms', chapter: 3 },
          { bookName: 'Psalms', chapter: 4 },
          { bookName: 'Psalms', chapter: 18 },
          { bookName: 'Psalms', chapter: 20 },
          { bookName: 'Psalms', chapter: 21 },
          { bookName: 'Psalms', chapter: 22 },
          { bookName: 'Psalms', chapter: 23 },
          { bookName: 'Psalms', chapter: 24 },
          { bookName: 'Psalms', chapter: 32 },
          { bookName: 'Psalms', chapter: 38 },
          { bookName: 'Psalms', chapter: 51 },
          { bookName: 'Psalms', chapter: 63 },
          { bookName: 'Psalms', chapter: 101 },
          { bookName: 'Psalms', chapter: 103 },
          { bookName: 'Psalms', chapter: 110 },
          { bookName: 'Psalms', chapter: 122 },
          { bookName: 'Psalms', chapter: 124 },
          { bookName: 'Psalms', chapter: 131 },
          { bookName: 'Psalms', chapter: 133 },
          { bookName: 'Psalms', chapter: 138 },
          { bookName: 'Psalms', chapter: 139 },
          { bookName: 'Psalms', chapter: 140 },
          { bookName: 'Psalms', chapter: 141 },
          { bookName: 'Psalms', chapter: 142 },
          { bookName: 'Psalms', chapter: 143 },
          { bookName: 'Psalms', chapter: 144 },
          { bookName: 'Psalms', chapter: 145 },
          { bookName: '1 Chronicles', chapter: 1 },
          { bookName: '1 Chronicles', chapter: 2 },
          { bookName: '1 Chronicles', chapter: 3 },
          { bookName: '1 Chronicles', chapter: 4 },
          { bookName: '1 Chronicles', chapter: 5 },
          { bookName: '1 Chronicles', chapter: 6 },
          { bookName: '1 Chronicles', chapter: 7 },
          { bookName: '1 Chronicles', chapter: 8 },
          { bookName: '1 Chronicles', chapter: 9 },
          { bookName: '1 Chronicles', chapter: 10 },
          { bookName: '1 Chronicles', chapter: 11 },
          { bookName: '1 Chronicles', chapter: 12 },
          { bookName: '1 Chronicles', chapter: 13 },
          { bookName: '1 Chronicles', chapter: 14 },
          { bookName: '1 Chronicles', chapter: 15 },
          { bookName: '1 Chronicles', chapter: 16 },
          { bookName: '1 Chronicles', chapter: 17 },
          { bookName: '1 Chronicles', chapter: 18 },
          { bookName: '1 Chronicles', chapter: 19 },
          { bookName: '1 Chronicles', chapter: 20 },
          { bookName: '1 Chronicles', chapter: 21 },
          { bookName: '1 Chronicles', chapter: 22 },
          { bookName: '1 Chronicles', chapter: 23 },
          { bookName: '1 Chronicles', chapter: 24 },
          { bookName: '1 Chronicles', chapter: 25 },
          { bookName: '1 Chronicles', chapter: 26 },
          { bookName: '1 Chronicles', chapter: 27 },
          { bookName: '1 Chronicles', chapter: 28 },
          { bookName: '1 Chronicles', chapter: 29 },
          { bookName: '1 Kings', chapter: 1 },
          { bookName: '1 Kings', chapter: 2 },
          { bookName: '1 Kings', chapter: 3 },
          { bookName: '1 Kings', chapter: 4 },
          { bookName: '1 Kings', chapter: 5 },
          { bookName: '1 Kings', chapter: 6 },
          { bookName: '1 Kings', chapter: 7 },
          { bookName: '1 Kings', chapter: 8 },
          { bookName: '1 Kings', chapter: 9 },
          { bookName: '1 Kings', chapter: 10 },
          { bookName: '1 Kings', chapter: 11 },
          { bookName: '2 Chronicles', chapter: 1 },
          { bookName: '2 Chronicles', chapter: 2 },
          { bookName: '2 Chronicles', chapter: 3 },
          { bookName: '2 Chronicles', chapter: 4 },
          { bookName: '2 Chronicles', chapter: 5 },
          { bookName: '2 Chronicles', chapter: 6 },
          { bookName: '2 Chronicles', chapter: 7 },
          { bookName: '2 Chronicles', chapter: 8 },
          { bookName: '2 Chronicles', chapter: 9 },
          { bookName: 'Psalms', chapter: 72 },
          { bookName: 'Psalms', chapter: 127 },
          { bookName: 'Proverbs', chapter: 1 },
          { bookName: 'Proverbs', chapter: 2 },
          { bookName: 'Proverbs', chapter: 3 },
          { bookName: 'Proverbs', chapter: 4 },
          { bookName: 'Proverbs', chapter: 5 },
          { bookName: 'Proverbs', chapter: 6 },
          { bookName: 'Proverbs', chapter: 7 },
          { bookName: 'Proverbs', chapter: 8 },
          { bookName: 'Proverbs', chapter: 9 },
          { bookName: 'Proverbs', chapter: 10 },
          { bookName: 'Proverbs', chapter: 11 },
          { bookName: 'Proverbs', chapter: 12 },
          { bookName: 'Proverbs', chapter: 13 },
          { bookName: 'Proverbs', chapter: 14 },
          { bookName: 'Proverbs', chapter: 15 },
          { bookName: 'Proverbs', chapter: 16 },
          { bookName: 'Proverbs', chapter: 17 },
          { bookName: 'Proverbs', chapter: 18 },
          { bookName: 'Proverbs', chapter: 19 },
          { bookName: 'Proverbs', chapter: 20 },
          { bookName: 'Proverbs', chapter: 21 },
          { bookName: 'Proverbs', chapter: 22 },
          { bookName: 'Proverbs', chapter: 23 },
          { bookName: 'Proverbs', chapter: 24 },
          { bookName: 'Proverbs', chapter: 25 },
          { bookName: 'Proverbs', chapter: 26 },
          { bookName: 'Proverbs', chapter: 27 },
          { bookName: 'Proverbs', chapter: 28 },
          { bookName: 'Proverbs', chapter: 29 },
          { bookName: 'Proverbs', chapter: 30 },
          { bookName: 'Proverbs', chapter: 31 },
          { bookName: 'Ecclesiastes', chapter: 1 },
          { bookName: 'Ecclesiastes', chapter: 2 },
          { bookName: 'Ecclesiastes', chapter: 3 },
          { bookName: 'Ecclesiastes', chapter: 4 },
          { bookName: 'Ecclesiastes', chapter: 5 },
          { bookName: 'Ecclesiastes', chapter: 6 },
          { bookName: 'Ecclesiastes', chapter: 7 },
          { bookName: 'Ecclesiastes', chapter: 8 },
          { bookName: 'Ecclesiastes', chapter: 9 },
          { bookName: 'Ecclesiastes', chapter: 10 },
          { bookName: 'Ecclesiastes', chapter: 11 },
          { bookName: 'Ecclesiastes', chapter: 12 },
          { bookName: 'Song of Solomon', chapter: 1 },
          { bookName: 'Song of Solomon', chapter: 2 },
          { bookName: 'Song of Solomon', chapter: 3 },
          { bookName: 'Song of Solomon', chapter: 4 },
          { bookName: 'Song of Solomon', chapter: 5 },
          { bookName: 'Song of Solomon', chapter: 6 },
          { bookName: 'Song of Solomon', chapter: 7 },
          { bookName: 'Song of Solomon', chapter: 8 },
        ]
      },
      {
        title: 'Divided Kingdom & Prophets',
        chapters: [
          { bookName: '1 Kings', chapter: 12 },
          { bookName: '1 Kings', chapter: 13 },
          { bookName: '1 Kings', chapter: 14 },
          { bookName: '1 Kings', chapter: 15 },
          { bookName: '1 Kings', chapter: 16 },
          { bookName: '1 Kings', chapter: 17 },
          { bookName: '1 Kings', chapter: 18 },
          { bookName: '1 Kings', chapter: 19 },
          { bookName: '1 Kings', chapter: 20 },
          { bookName: '1 Kings', chapter: 21 },
          { bookName: '1 Kings', chapter: 22 },
          { bookName: '2 Kings', chapter: 1 },
          { bookName: '2 Kings', chapter: 2 },
          { bookName: '2 Kings', chapter: 3 },
          { bookName: '2 Kings', chapter: 4 },
          { bookName: '2 Kings', chapter: 5 },
          { bookName: '2 Kings', chapter: 6 },
          { bookName: '2 Kings', chapter: 7 },
          { bookName: '2 Kings', chapter: 8 },
          { bookName: '2 Kings', chapter: 9 },
          { bookName: '2 Kings', chapter: 10 },
          { bookName: '2 Kings', chapter: 11 },
          { bookName: '2 Kings', chapter: 12 },
          { bookName: '2 Kings', chapter: 13 },
          { bookName: '2 Kings', chapter: 14 },
          { bookName: '2 Kings', chapter: 15 },
          { bookName: '2 Kings', chapter: 16 },
          { bookName: '2 Kings', chapter: 17 },
          { bookName: '2 Chronicles', chapter: 10 },
          { bookName: '2 Chronicles', chapter: 11 },
          { bookName: '2 Chronicles', chapter: 12 },
          { bookName: '2 Chronicles', chapter: 13 },
          { bookName: '2 Chronicles', chapter: 14 },
          { bookName: '2 Chronicles', chapter: 15 },
          { bookName: '2 Chronicles', chapter: 16 },
          { bookName: '2 Chronicles', chapter: 17 },
          { bookName: '2 Chronicles', chapter: 18 },
          { bookName: '2 Chronicles', chapter: 19 },
          { bookName: '2 Chronicles', chapter: 20 },
          { bookName: '2 Chronicles', chapter: 21 },
          { bookName: '2 Chronicles', chapter: 22 },
          { bookName: '2 Chronicles', chapter: 23 },
          { bookName: '2 Chronicles', chapter: 24 },
          { bookName: '2 Chronicles', chapter: 25 },
          { bookName: '2 Chronicles', chapter: 26 },
          { bookName: '2 Chronicles', chapter: 27 },
          { bookName: '2 Chronicles', chapter: 28 },
          { bookName: 'Psalms', chapter: 42 },
          { bookName: 'Psalms', chapter: 43 },
          { bookName: 'Psalms', chapter: 44 },
          { bookName: 'Psalms', chapter: 45 },
          { bookName: 'Psalms', chapter: 46 },
          { bookName: 'Psalms', chapter: 47 },
          { bookName: 'Psalms', chapter: 48 },
          { bookName: 'Psalms', chapter: 49 },
          { bookName: 'Psalms', chapter: 73 },
          { bookName: 'Psalms', chapter: 74 },
          { bookName: 'Psalms', chapter: 75 },
          { bookName: 'Psalms', chapter: 76 },
          { bookName: 'Psalms', chapter: 77 },
          { bookName: 'Psalms', chapter: 78 },
          { bookName: 'Psalms', chapter: 79 },
          { bookName: 'Psalms', chapter: 80 },
          { bookName: 'Psalms', chapter: 81 },
          { bookName: 'Psalms', chapter: 82 },
          { bookName: 'Psalms', chapter: 83 },
          { bookName: 'Psalms', chapter: 84 },
          { bookName: 'Psalms', chapter: 85 },
          { bookName: 'Psalms', chapter: 87 },
          { bookName: 'Psalms', chapter: 88 },
          { bookName: 'Jonah', chapter: 1 },
          { bookName: 'Jonah', chapter: 2 },
          { bookName: 'Jonah', chapter: 3 },
          { bookName: 'Jonah', chapter: 4 },
          { bookName: 'Amos', chapter: 1 },
          { bookName: 'Amos', chapter: 2 },
          { bookName: 'Amos', chapter: 3 },
          { bookName: 'Amos', chapter: 4 },
          { bookName: 'Amos', chapter: 5 },
          { bookName: 'Amos', chapter: 6 },
          { bookName: 'Amos', chapter: 7 },
          { bookName: 'Amos', chapter: 8 },
          { bookName: 'Amos', chapter: 9 },
          { bookName: 'Hosea', chapter: 1 },
          { bookName: 'Hosea', chapter: 2 },
          { bookName: 'Hosea', chapter: 3 },
          { bookName: 'Hosea', chapter: 4 },
          { bookName: 'Hosea', chapter: 5 },
          { bookName: 'Hosea', chapter: 6 },
          { bookName: 'Hosea', chapter: 7 },
          { bookName: 'Hosea', chapter: 8 },
          { bookName: 'Hosea', chapter: 9 },
          { bookName: 'Hosea', chapter: 10 },
          { bookName: 'Hosea', chapter: 11 },
          { bookName: 'Hosea', chapter: 12 },
          { bookName: 'Hosea', chapter: 13 },
          { bookName: 'Hosea', chapter: 14 },
          { bookName: 'Isaiah', chapter: 1 },
          { bookName: 'Isaiah', chapter: 2 },
          { bookName: 'Isaiah', chapter: 3 },
          { bookName: 'Isaiah', chapter: 4 },
          { bookName: 'Isaiah', chapter: 5 },
          { bookName: 'Isaiah', chapter: 6 },
          { bookName: 'Isaiah', chapter: 7 },
          { bookName: 'Isaiah', chapter: 8 },
          { bookName: 'Isaiah', chapter: 9 },
          { bookName: 'Isaiah', chapter: 10 },
          { bookName: 'Isaiah', chapter: 11 },
          { bookName: 'Isaiah', chapter: 12 },
          { bookName: 'Isaiah', chapter: 13 },
          { bookName: 'Isaiah', chapter: 14 },
          { bookName: 'Isaiah', chapter: 15 },
          { bookName: 'Isaiah', chapter: 16 },
          { bookName: 'Isaiah', chapter: 17 },
          { bookName: 'Isaiah', chapter: 18 },
          { bookName: 'Isaiah', chapter: 19 },
          { bookName: 'Isaiah', chapter: 20 },
          { bookName: 'Isaiah', chapter: 21 },
          { bookName: 'Isaiah', chapter: 22 },
          { bookName: 'Isaiah', chapter: 23 },
          { bookName: 'Isaiah', chapter: 24 },
          { bookName: 'Isaiah', chapter: 25 },
          { bookName: 'Isaiah', chapter: 26 },
          { bookName: 'Isaiah', chapter: 27 },
          { bookName: 'Isaiah', chapter: 28 },
          { bookName: 'Isaiah', chapter: 29 },
          { bookName: 'Isaiah', chapter: 30 },
          { bookName: 'Isaiah', chapter: 31 },
          { bookName: 'Isaiah', chapter: 32 },
          { bookName: 'Isaiah', chapter: 33 },
          { bookName: 'Isaiah', chapter: 34 },
          { bookName: 'Isaiah', chapter: 35 },
          { bookName: 'Isaiah', chapter: 36 },
          { bookName: 'Isaiah', chapter: 37 },
          { bookName: 'Isaiah', chapter: 38 },
          { bookName: 'Isaiah', chapter: 39 },
          { bookName: 'Micah', chapter: 1 },
          { bookName: 'Micah', chapter: 2 },
          { bookName: 'Micah', chapter: 3 },
          { bookName: 'Micah', chapter: 4 },
          { bookName: 'Micah', chapter: 5 },
          { bookName: 'Micah', chapter: 6 },
          { bookName: 'Micah', chapter: 7 },
        ]
      },
      {
        title: 'Judah Falls & Exile',
        chapters: [
          { bookName: '2 Kings', chapter: 18 },
          { bookName: '2 Kings', chapter: 19 },
          { bookName: '2 Kings', chapter: 20 },
          { bookName: '2 Kings', chapter: 21 },
          { bookName: '2 Kings', chapter: 22 },
          { bookName: '2 Kings', chapter: 23 },
          { bookName: '2 Kings', chapter: 24 },
          { bookName: '2 Kings', chapter: 25 },
          { bookName: '2 Chronicles', chapter: 29 },
          { bookName: '2 Chronicles', chapter: 30 },
          { bookName: '2 Chronicles', chapter: 31 },
          { bookName: '2 Chronicles', chapter: 32 },
          { bookName: '2 Chronicles', chapter: 33 },
          { bookName: '2 Chronicles', chapter: 34 },
          { bookName: '2 Chronicles', chapter: 35 },
          { bookName: '2 Chronicles', chapter: 36 },
          { bookName: 'Nahum', chapter: 1 },
          { bookName: 'Nahum', chapter: 2 },
          { bookName: 'Nahum', chapter: 3 },
          { bookName: 'Zephaniah', chapter: 1 },
          { bookName: 'Zephaniah', chapter: 2 },
          { bookName: 'Zephaniah', chapter: 3 },
          { bookName: 'Habakkuk', chapter: 1 },
          { bookName: 'Habakkuk', chapter: 2 },
          { bookName: 'Habakkuk', chapter: 3 },
          { bookName: 'Jeremiah', chapter: 1 },
          { bookName: 'Jeremiah', chapter: 2 },
          { bookName: 'Jeremiah', chapter: 3 },
          { bookName: 'Jeremiah', chapter: 4 },
          { bookName: 'Jeremiah', chapter: 5 },
          { bookName: 'Jeremiah', chapter: 6 },
          { bookName: 'Jeremiah', chapter: 7 },
          { bookName: 'Jeremiah', chapter: 8 },
          { bookName: 'Jeremiah', chapter: 9 },
          { bookName: 'Jeremiah', chapter: 10 },
          { bookName: 'Jeremiah', chapter: 11 },
          { bookName: 'Jeremiah', chapter: 12 },
          { bookName: 'Jeremiah', chapter: 13 },
          { bookName: 'Jeremiah', chapter: 14 },
          { bookName: 'Jeremiah', chapter: 15 },
          { bookName: 'Jeremiah', chapter: 16 },
          { bookName: 'Jeremiah', chapter: 17 },
          { bookName: 'Jeremiah', chapter: 18 },
          { bookName: 'Jeremiah', chapter: 19 },
          { bookName: 'Jeremiah', chapter: 20 },
          { bookName: 'Jeremiah', chapter: 21 },
          { bookName: 'Jeremiah', chapter: 22 },
          { bookName: 'Jeremiah', chapter: 23 },
          { bookName: 'Jeremiah', chapter: 24 },
          { bookName: 'Jeremiah', chapter: 25 },
          { bookName: 'Jeremiah', chapter: 26 },
          { bookName: 'Jeremiah', chapter: 27 },
          { bookName: 'Jeremiah', chapter: 28 },
          { bookName: 'Jeremiah', chapter: 29 },
          { bookName: 'Jeremiah', chapter: 30 },
          { bookName: 'Jeremiah', chapter: 31 },
          { bookName: 'Jeremiah', chapter: 32 },
          { bookName: 'Jeremiah', chapter: 33 },
          { bookName: 'Jeremiah', chapter: 34 },
          { bookName: 'Jeremiah', chapter: 35 },
          { bookName: 'Jeremiah', chapter: 36 },
          { bookName: 'Jeremiah', chapter: 37 },
          { bookName: 'Jeremiah', chapter: 38 },
          { bookName: 'Jeremiah', chapter: 39 },
          { bookName: 'Jeremiah', chapter: 40 },
          { bookName: 'Jeremiah', chapter: 41 },
          { bookName: 'Jeremiah', chapter: 42 },
          { bookName: 'Jeremiah', chapter: 43 },
          { bookName: 'Jeremiah', chapter: 44 },
          { bookName: 'Jeremiah', chapter: 45 },
          { bookName: 'Jeremiah', chapter: 46 },
          { bookName: 'Jeremiah', chapter: 47 },
          { bookName: 'Jeremiah', chapter: 48 },
          { bookName: 'Jeremiah', chapter: 49 },
          { bookName: 'Jeremiah', chapter: 50 },
          { bookName: 'Jeremiah', chapter: 51 },
          { bookName: 'Jeremiah', chapter: 52 },
          { bookName: 'Lamentations', chapter: 1 },
          { bookName: 'Lamentations', chapter: 2 },
          { bookName: 'Lamentations', chapter: 3 },
          { bookName: 'Lamentations', chapter: 4 },
          { bookName: 'Lamentations', chapter: 5 },
          { bookName: 'Ezekiel', chapter: 1 },
          { bookName: 'Ezekiel', chapter: 2 },
          { bookName: 'Ezekiel', chapter: 3 },
          { bookName: 'Ezekiel', chapter: 4 },
          { bookName: 'Ezekiel', chapter: 5 },
          { bookName: 'Ezekiel', chapter: 6 },
          { bookName: 'Ezekiel', chapter: 7 },
          { bookName: 'Ezekiel', chapter: 8 },
          { bookName: 'Ezekiel', chapter: 9 },
          { bookName: 'Ezekiel', chapter: 10 },
          { bookName: 'Ezekiel', chapter: 11 },
          { bookName: 'Ezekiel', chapter: 12 },
          { bookName: 'Ezekiel', chapter: 13 },
          { bookName: 'Ezekiel', chapter: 14 },
          { bookName: 'Ezekiel', chapter: 15 },
          { bookName: 'Ezekiel', chapter: 16 },
          { bookName: 'Ezekiel', chapter: 17 },
          { bookName: 'Ezekiel', chapter: 18 },
          { bookName: 'Ezekiel', chapter: 19 },
          { bookName: 'Ezekiel', chapter: 20 },
          { bookName: 'Ezekiel', chapter: 21 },
          { bookName: 'Ezekiel', chapter: 22 },
          { bookName: 'Ezekiel', chapter: 23 },
          { bookName: 'Ezekiel', chapter: 24 },
          { bookName: 'Ezekiel', chapter: 25 },
          { bookName: 'Ezekiel', chapter: 26 },
          { bookName: 'Ezekiel', chapter: 27 },
          { bookName: 'Ezekiel', chapter: 28 },
          { bookName: 'Ezekiel', chapter: 29 },
          { bookName: 'Ezekiel', chapter: 30 },
          { bookName: 'Ezekiel', chapter: 31 },
          { bookName: 'Ezekiel', chapter: 32 },
          { bookName: 'Ezekiel', chapter: 33 },
          { bookName: 'Ezekiel', chapter: 34 },
          { bookName: 'Ezekiel', chapter: 35 },
          { bookName: 'Ezekiel', chapter: 36 },
          { bookName: 'Ezekiel', chapter: 37 },
          { bookName: 'Ezekiel', chapter: 38 },
          { bookName: 'Ezekiel', chapter: 39 },
          { bookName: 'Ezekiel', chapter: 40 },
          { bookName: 'Ezekiel', chapter: 41 },
          { bookName: 'Ezekiel', chapter: 42 },
          { bookName: 'Ezekiel', chapter: 43 },
          { bookName: 'Ezekiel', chapter: 44 },
          { bookName: 'Ezekiel', chapter: 45 },
          { bookName: 'Ezekiel', chapter: 46 },
          { bookName: 'Ezekiel', chapter: 47 },
          { bookName: 'Ezekiel', chapter: 48 },
          { bookName: 'Daniel', chapter: 1 },
          { bookName: 'Daniel', chapter: 2 },
          { bookName: 'Daniel', chapter: 3 },
          { bookName: 'Daniel', chapter: 4 },
          { bookName: 'Daniel', chapter: 5 },
          { bookName: 'Daniel', chapter: 6 },
          { bookName: 'Daniel', chapter: 7 },
          { bookName: 'Daniel', chapter: 8 },
          { bookName: 'Daniel', chapter: 9 },
          { bookName: 'Daniel', chapter: 10 },
          { bookName: 'Daniel', chapter: 11 },
          { bookName: 'Daniel', chapter: 12 },
          { bookName: 'Psalms', chapter: 102 },
          { bookName: 'Psalms', chapter: 137 },
        ]
      },
      {
        title: 'Return & Restoration',
        chapters: [
          { bookName: 'Ezra', chapter: 1 },
          { bookName: 'Ezra', chapter: 2 },
          { bookName: 'Ezra', chapter: 3 },
          { bookName: 'Ezra', chapter: 4 },
          { bookName: 'Ezra', chapter: 5 },
          { bookName: 'Ezra', chapter: 6 },
          { bookName: 'Haggai', chapter: 1 },
          { bookName: 'Haggai', chapter: 2 },
          { bookName: 'Zechariah', chapter: 1 },
          { bookName: 'Zechariah', chapter: 2 },
          { bookName: 'Zechariah', chapter: 3 },
          { bookName: 'Zechariah', chapter: 4 },
          { bookName: 'Zechariah', chapter: 5 },
          { bookName: 'Zechariah', chapter: 6 },
          { bookName: 'Zechariah', chapter: 7 },
          { bookName: 'Zechariah', chapter: 8 },
          { bookName: 'Zechariah', chapter: 9 },
          { bookName: 'Zechariah', chapter: 10 },
          { bookName: 'Zechariah', chapter: 11 },
          { bookName: 'Zechariah', chapter: 12 },
          { bookName: 'Zechariah', chapter: 13 },
          { bookName: 'Zechariah', chapter: 14 },
          { bookName: 'Ezra', chapter: 7 },
          { bookName: 'Ezra', chapter: 8 },
          { bookName: 'Ezra', chapter: 9 },
          { bookName: 'Ezra', chapter: 10 },
          { bookName: 'Esther', chapter: 1 },
          { bookName: 'Esther', chapter: 2 },
          { bookName: 'Esther', chapter: 3 },
          { bookName: 'Esther', chapter: 4 },
          { bookName: 'Esther', chapter: 5 },
          { bookName: 'Esther', chapter: 6 },
          { bookName: 'Esther', chapter: 7 },
          { bookName: 'Esther', chapter: 8 },
          { bookName: 'Esther', chapter: 9 },
          { bookName: 'Esther', chapter: 10 },
          { bookName: 'Nehemiah', chapter: 1 },
          { bookName: 'Nehemiah', chapter: 2 },
          { bookName: 'Nehemiah', chapter: 3 },
          { bookName: 'Nehemiah', chapter: 4 },
          { bookName: 'Nehemiah', chapter: 5 },
          { bookName: 'Nehemiah', chapter: 6 },
          { bookName: 'Nehemiah', chapter: 7 },
          { bookName: 'Nehemiah', chapter: 8 },
          { bookName: 'Nehemiah', chapter: 9 },
          { bookName: 'Nehemiah', chapter: 10 },
          { bookName: 'Nehemiah', chapter: 11 },
          { bookName: 'Nehemiah', chapter: 12 },
          { bookName: 'Nehemiah', chapter: 13 },
          { bookName: 'Psalms', chapter: 120 },
          { bookName: 'Psalms', chapter: 121 },
          { bookName: 'Psalms', chapter: 122 },
          { bookName: 'Psalms', chapter: 123 },
          { bookName: 'Psalms', chapter: 124 },
          { bookName: 'Psalms', chapter: 125 },
          { bookName: 'Psalms', chapter: 126 },
          { bookName: 'Psalms', chapter: 127 },
          { bookName: 'Psalms', chapter: 128 },
          { bookName: 'Psalms', chapter: 129 },
          { bookName: 'Psalms', chapter: 130 },
          { bookName: 'Psalms', chapter: 131 },
          { bookName: 'Psalms', chapter: 132 },
          { bookName: 'Psalms', chapter: 133 },
          { bookName: 'Psalms', chapter: 134 },
          { bookName: 'Malachi', chapter: 1 },
          { bookName: 'Malachi', chapter: 2 },
          { bookName: 'Malachi', chapter: 3 },
          { bookName: 'Malachi', chapter: 4 },
          { bookName: 'Psalms', chapter: 146 },
          { bookName: 'Psalms', chapter: 147 },
          { bookName: 'Psalms', chapter: 148 },
          { bookName: 'Psalms', chapter: 149 },
          { bookName: 'Psalms', chapter: 150 },
        ]
      }
    ]
  },
};

/**
 * Flatten a character's sections into a single chapter list
 */
export function flattenCharacterSections(characterKey) {
  const character = CHARACTER_LIBRARY[characterKey];
  if (!character) return [];
  
  const chapters = [];
  character.sections.forEach(section => {
    section.chapters.forEach(ch => {
      chapters.push(ch);
    });
  });
  
  return chapters;
}