
export const CURATED_PLANS = {
  WHO_IS_JESUS: [
    // SECTION 1: PROMISED MESSIAH (PROPHECY)
    { bookName: 'Genesis', chapter: 3 },
    { bookName: 'Genesis', chapter: 12 },
    { bookName: 'Genesis', chapter: 22 },
    { bookName: 'Deuteronomy', chapter: 18 },
    { bookName: 'Psalms', chapter: 2 },
    { bookName: 'Psalms', chapter: 22 },
    { bookName: 'Psalms', chapter: 110 },
    { bookName: 'Isaiah', chapter: 7 },
    { bookName: 'Isaiah', chapter: 9 },
    { bookName: 'Isaiah', chapter: 11 },
    { bookName: 'Isaiah', chapter: 53 },
    { bookName: 'Micah', chapter: 5 },
    { bookName: 'Daniel', chapter: 7 },
    // SECTION 2: INCARNATION & IDENTITY
    { bookName: 'Matthew', chapter: 1 },
    { bookName: 'Matthew', chapter: 2 },
    { bookName: 'Luke', chapter: 1 },
    { bookName: 'Luke', chapter: 2 },
    { bookName: 'John', chapter: 1 },
    { bookName: 'Matthew', chapter: 3 },
    { bookName: 'Luke', chapter: 3 },
    // SECTION 3: MINISTRY & MESSAGE
    { bookName: 'Matthew', chapter: 5 },
    { bookName: 'Matthew', chapter: 6 },
    { bookName: 'Matthew', chapter: 7 },
    { bookName: 'Matthew', chapter: 11 },
    { bookName: 'Matthew', chapter: 12 },
    { bookName: 'Matthew', chapter: 13 },
    { bookName: 'Luke', chapter: 4 },
    { bookName: 'Luke', chapter: 7 },
    { bookName: 'Luke', chapter: 9 },
    { bookName: 'Luke', chapter: 15 },
    { bookName: 'John', chapter: 3 },
    { bookName: 'John', chapter: 6 },
    { bookName: 'John', chapter: 8 },
    { bookName: 'John', chapter: 10 },
    { bookName: 'John', chapter: 11 },
    // SECTION 4: REJECTION, CROSS & ATONEMENT
    { bookName: 'Matthew', chapter: 26 },
    { bookName: 'Matthew', chapter: 27 },
    { bookName: 'Luke', chapter: 22 },
    { bookName: 'Luke', chapter: 23 },
    { bookName: 'John', chapter: 18 },
    { bookName: 'John', chapter: 19 },
    { bookName: 'Psalms', chapter: 22 },
    { bookName: 'Isaiah', chapter: 53 },
    // SECTION 5: RESURRECTION, EXALTATION & ETERNAL REIGN
    { bookName: 'Matthew', chapter: 28 },
    { bookName: 'Luke', chapter: 24 },
    { bookName: 'John', chapter: 20 },
    { bookName: 'John', chapter: 21 },
    { bookName: 'Acts', chapter: 1 },
    { bookName: 'Acts', chapter: 2 },
    { bookName: 'Philippians', chapter: 2 },
    { bookName: 'Colossians', chapter: 1 },
    { bookName: 'Hebrews', chapter: 1 },
    { bookName: 'Hebrews', chapter: 7 },
    { bookName: 'Revelation', chapter: 1 },
    { bookName: 'Revelation', chapter: 5 },
    { bookName: 'Revelation', chapter: 19 },
  ],
  LEADERSHIP_INTENSIVE: [
    // Nehemiah 1–13
    { bookName: 'Nehemiah', chapter: 1 },
    { bookName: 'Nehemiah', chapter: 2 },
    { bookName: 'Nehemiah', chapter: 3 },
    { bookName: 'Nehemiah', chapter: 4 },
    { bookName: 'Nehemiah', chapter: 5 },
    { bookName: 'Nehemiah', chapter: 6 },
    { bookName: 'Nehemiah', chapter: 7 },
    { bookName: 'Nehemiah', chapter: 8 },
    { bookName: 'Nehemiah', chapter: 9 },
    { bookName: 'Nehemiah', chapter: 10 },
    { bookName: 'Nehemiah', chapter: 11 },
    { bookName: 'Nehemiah', chapter: 12 },
    { bookName: 'Nehemiah', chapter: 13 },
    // 1 Timothy 1–6
    { bookName: '1 Timothy', chapter: 1 },
    { bookName: '1 Timothy', chapter: 2 },
    { bookName: '1 Timothy', chapter: 3 },
    { bookName: '1 Timothy', chapter: 4 },
    { bookName: '1 Timothy', chapter: 5 },
    { bookName: '1 Timothy', chapter: 6 },
    // 2 Timothy 1–4
    { bookName: '2 Timothy', chapter: 1 },
    { bookName: '2 Timothy', chapter: 2 },
    { bookName: '2 Timothy', chapter: 3 },
    { bookName: '2 Timothy', chapter: 4 },
    // Titus 1–3
    { bookName: 'Titus', chapter: 1 },
    { bookName: 'Titus', chapter: 2 },
    { bookName: 'Titus', chapter: 3 },
    // Exodus 18–20, 23–25, 32–34, 36–40
    { bookName: 'Exodus', chapter: 18 },
    { bookName: 'Exodus', chapter: 19 },
    { bookName: 'Exodus', chapter: 20 },
    { bookName: 'Exodus', chapter: 23 },
    { bookName: 'Exodus', chapter: 24 },
    { bookName: 'Exodus', chapter: 25 },
    { bookName: 'Exodus', chapter: 32 },
    { bookName: 'Exodus', chapter: 33 },
    { bookName: 'Exodus', chapter: 34 },
    { bookName: 'Exodus', chapter: 36 },
    { bookName: 'Exodus', chapter: 37 },
    { bookName: 'Exodus', chapter: 38 },
    { bookName: 'Exodus', chapter: 39 },
    { bookName: 'Exodus', chapter: 40 },
    // 1 Samuel 12–17, 24–26, 30
    { bookName: '1 Samuel', chapter: 12 },
    { bookName: '1 Samuel', chapter: 13 },
    { bookName: '1 Samuel', chapter: 14 },
    { bookName: '1 Samuel', chapter: 15 },
    { bookName: '1 Samuel', chapter: 16 },
    { bookName: '1 Samuel', chapter: 17 },
    { bookName: '1 Samuel', chapter: 24 },
    { bookName: '1 Samuel', chapter: 25 },
    { bookName: '1 Samuel', chapter: 26 },
    { bookName: '1 Samuel', chapter: 30 },
    // Matthew 20–28
    { bookName: 'Matthew', chapter: 20 },
    { bookName: 'Matthew', chapter: 21 },
    { bookName: 'Matthew', chapter: 22 },
    { bookName: 'Matthew', chapter: 23 },
    { bookName: 'Matthew', chapter: 24 },
    { bookName: 'Matthew', chapter: 25 },
    { bookName: 'Matthew', chapter: 26 },
    { bookName: 'Matthew', chapter: 27 },
    { bookName: 'Matthew', chapter: 28 },
    // Acts 1–7, 20
    { bookName: 'Acts', chapter: 1 },
    { bookName: 'Acts', chapter: 2 },
    { bookName: 'Acts', chapter: 3 },
    { bookName: 'Acts', chapter: 4 },
    { bookName: 'Acts', chapter: 5 },
    { bookName: 'Acts', chapter: 6 },
    { bookName: 'Acts', chapter: 7 },
    { bookName: 'Acts', chapter: 20 },
  ],
  WISDOM_PLUNGE: [
    // Proverbs 1–31
    { bookName: 'Proverbs', chapter: 1 },
    { bookName: 'Proverbs', chapter: 2 },
    { bookName: 'Proverbs', chapter: 3 },
    { bookName: 'Proverbs', chapter: 4 },
    { bookName: 'Proverbs', chapter: 5 },
    { bookName: 'Proverbs', chapter: 6 },
    { bookName: 'Proverbs', chapter: 7 },
    { bookName: 'Proverbs', chapter: 8 },
    { bookName: 'Proverbs', chapter: 9 },
    { bookName: 'Proverbs', chapter: 10 },
    { bookName: 'Proverbs', chapter: 11 },
    { bookName: 'Proverbs', chapter: 12 },
    { bookName: 'Proverbs', chapter: 13 },
    { bookName: 'Proverbs', chapter: 14 },
    { bookName: 'Proverbs', chapter: 15 },
    { bookName: 'Proverbs', chapter: 16 },
    { bookName: 'Proverbs', chapter: 17 },
    { bookName: 'Proverbs', chapter: 18 },
    { bookName: 'Proverbs', chapter: 19 },
    { bookName: 'Proverbs', chapter: 20 },
    { bookName: 'Proverbs', chapter: 21 },
    { bookName: 'Proverbs', chapter: 22 },
    { bookName: 'Proverbs', chapter: 23 },
    { bookName: 'Proverbs', chapter: 24 },
    { bookName: 'Proverbs', chapter: 25 },
    { bookName: 'Proverbs', chapter: 26 },
    { bookName: 'Proverbs', chapter: 27 },
    { bookName: 'Proverbs', chapter: 28 },
    { bookName: 'Proverbs', chapter: 29 },
    { bookName: 'Proverbs', chapter: 30 },
    { bookName: 'Proverbs', chapter: 31 },
    // Ecclesiastes 1–12
    { bookName: 'Ecclesiastes', chapter: 1 },
    { bookName: 'Ecclesiastes', chapter: 2 },
    { bookName: 'Ecclesiastes', chapter: 3 },
    { bookName: 'Ecclesiastes', chapter: 4 },
    { bookName: 'Ecclesiastes', chapter: 5 },
    { bookName: 'Ecclesiastes', chapter: 6 },
    { bookName: 'Ecclesiastes', chapter: 7 },
    { bookName: 'Ecclesiastes', chapter: 8 },
    { bookName: 'Ecclesiastes', chapter: 9 },
    { bookName: 'Ecclesiastes', chapter: 10 },
    { bookName: 'Ecclesiastes', chapter: 11 },
    { bookName: 'Ecclesiastes', chapter: 12 },
    // James 1–5
    { bookName: 'James', chapter: 1 },
    { bookName: 'James', chapter: 2 },
    { bookName: 'James', chapter: 3 },
    { bookName: 'James', chapter: 4 },
    { bookName: 'James', chapter: 5 },
    // Job 1–14, 28, 38–42
    { bookName: 'Job', chapter: 1 },
    { bookName: 'Job', chapter: 2 },
    { bookName: 'Job', chapter: 3 },
    { bookName: 'Job', chapter: 4 },
    { bookName: 'Job', chapter: 5 },
    { bookName: 'Job', chapter: 6 },
    { bookName: 'Job', chapter: 7 },
    { bookName: 'Job', chapter: 8 },
    { bookName: 'Job', chapter: 9 },
    { bookName: 'Job', chapter: 10 },
    { bookName: 'Job', chapter: 11 },
    { bookName: 'Job', chapter: 12 },
    { bookName: 'Job', chapter: 13 },
    { bookName: 'Job', chapter: 14 },
    { bookName: 'Job', chapter: 28 },
    { bookName: 'Job', chapter: 38 },
    { bookName: 'Job', chapter: 39 },
    { bookName: 'Job', chapter: 40 },
    { bookName: 'Job', chapter: 41 },
    { bookName: 'Job', chapter: 42 },
    // Psalms 1, 19, 37, 49, 73, 90, 119
    { bookName: 'Psalms', chapter: 1 },
    { bookName: 'Psalms', chapter: 19 },
    { bookName: 'Psalms', chapter: 37 },
    { bookName: 'Psalms', chapter: 49 },
    { bookName: 'Psalms', chapter: 73 },
    { bookName: 'Psalms', chapter: 90 },
    { bookName: 'Psalms', chapter: 119 },
  ],
  INTENTIONAL_MOTHERHOOD: [
    // Day 1: Proverbs 31, Psalm 127
    { bookName: 'Proverbs', chapter: 31 },
    { bookName: 'Psalms', chapter: 127 },
    // Day 2: Deuteronomy 6, Psalm 78
    { bookName: 'Deuteronomy', chapter: 6 },
    { bookName: 'Psalms', chapter: 78 },
    // Day 3: 1 Samuel 1, 1 Samuel 2
    { bookName: '1 Samuel', chapter: 1 },
    { bookName: '1 Samuel', chapter: 2 },
    // Day 4: Luke 1, Luke 2
    { bookName: 'Luke', chapter: 1 },
    { bookName: 'Luke', chapter: 2 },
    // Day 5: Titus 2, Proverbs 14
    { bookName: 'Titus', chapter: 2 },
    { bookName: 'Proverbs', chapter: 14 },
    // Day 6: Isaiah 40, Isaiah 49
    { bookName: 'Isaiah', chapter: 40 },
    { bookName: 'Isaiah', chapter: 49 },
    // Day 7: 2 Timothy 1, 2 Timothy 3
    { bookName: '2 Timothy', chapter: 1 },
    { bookName: '2 Timothy', chapter: 3 },
    // Day 8: Psalm 128, Psalm 139
    { bookName: 'Psalms', chapter: 128 },
    { bookName: 'Psalms', chapter: 139 },
    // Day 9: Proverbs 22, Proverbs 23
    { bookName: 'Proverbs', chapter: 22 },
    { bookName: 'Proverbs', chapter: 23 },
    // Day 10: Joshua 24, Psalm 127
    { bookName: 'Joshua', chapter: 24 },
    { bookName: 'Psalms', chapter: 127 },
  ],
  GODLY_MAN: [
    // Day 1: Joshua 1, Psalm 1
    { bookName: 'Joshua', chapter: 1 },
    { bookName: 'Psalms', chapter: 1 },
    // Day 2: Proverbs 4, Proverbs 20
    { bookName: 'Proverbs', chapter: 4 },
    { bookName: 'Proverbs', chapter: 20 },
    // Day 3: Micah 6, Psalm 15
    { bookName: 'Micah', chapter: 6 },
    { bookName: 'Psalms', chapter: 15 },
    // Day 4: 1 Kings 2, Proverbs 16
    { bookName: '1 Kings', chapter: 2 },
    { bookName: 'Proverbs', chapter: 16 },
    // Day 5: Ephesians 5, Ephesians 6
    { bookName: 'Ephesians', chapter: 5 },
    { bookName: 'Ephesians', chapter: 6 },
    // Day 6: 1 Corinthians 9, 1 Corinthians 16
    { bookName: '1 Corinthians', chapter: 9 },
    { bookName: '1 Corinthians', chapter: 16 },
    // Day 7: 1 Timothy 6, Titus 1
    { bookName: '1 Timothy', chapter: 6 },
    { bookName: 'Titus', chapter: 1 },
    // Day 8: James 1, James 2
    { bookName: 'James', chapter: 1 },
    { bookName: 'James', chapter: 2 },
    // Day 9: Psalm 112, Psalm 128
    { bookName: 'Psalms', chapter: 112 },
    { bookName: 'Psalms', chapter: 128 },
    // Day 10: 2 Timothy 2, Psalm 37
    { bookName: '2 Timothy', chapter: 2 },
    { bookName: 'Psalms', chapter: 37 },
  ],
  LIVE_WITH_PURPOSE: [
    // Day 1: Romans 12, Proverbs 16
    { bookName: 'Romans', chapter: 12 },
    { bookName: 'Proverbs', chapter: 16 },
    // Day 2: Psalm 37, Psalm 90
    { bookName: 'Psalms', chapter: 37 },
    { bookName: 'Psalms', chapter: 90 },
    // Day 3: Matthew 6, Matthew 7
    { bookName: 'Matthew', chapter: 6 },
    { bookName: 'Matthew', chapter: 7 },
    // Day 4: Ecclesiastes 3, Ecclesiastes 12
    { bookName: 'Ecclesiastes', chapter: 3 },
    { bookName: 'Ecclesiastes', chapter: 12 },
    // Day 5: Colossians 1, Colossians 3
    { bookName: 'Colossians', chapter: 1 },
    { bookName: 'Colossians', chapter: 3 },
    // Day 6: Ephesians 2, Ephesians 4
    { bookName: 'Ephesians', chapter: 2 },
    { bookName: 'Ephesians', chapter: 4 },
    // Day 7: Philippians 1, Philippians 3
    { bookName: 'Philippians', chapter: 1 },
    { bookName: 'Philippians', chapter: 3 },
    // Day 8: 2 Timothy 2, Proverbs 4
    { bookName: '2 Timothy', chapter: 2 },
    { bookName: 'Proverbs', chapter: 4 },
    // Day 9: Hebrews 12, Hebrews 13
    { bookName: 'Hebrews', chapter: 12 },
    { bookName: 'Hebrews', chapter: 13 },
    // Day 10: Joshua 1, Psalm 1
    { bookName: 'Joshua', chapter: 1 },
    { bookName: 'Psalms', chapter: 1 },
  ],
  KNOW_KING_DAVID: [
    // Day 1: 1 Samuel 16, Psalm 78
    { bookName: '1 Samuel', chapter: 16 },
    { bookName: 'Psalms', chapter: 78 },
    // Day 2: 1 Samuel 17, Psalm 144
    { bookName: '1 Samuel', chapter: 17 },
    { bookName: 'Psalms', chapter: 144 },
    // Day 3: 1 Samuel 18, 1 Samuel 19
    { bookName: '1 Samuel', chapter: 18 },
    { bookName: '1 Samuel', chapter: 19 },
    // Day 4: 1 Samuel 24, 1 Samuel 26
    { bookName: '1 Samuel', chapter: 24 },
    { bookName: '1 Samuel', chapter: 26 },
    // Day 5: Psalm 57, Psalm 59
    { bookName: 'Psalms', chapter: 57 },
    { bookName: 'Psalms', chapter: 59 },
    // Day 6: 2 Samuel 5, Psalm 2
    { bookName: '2 Samuel', chapter: 5 },
    { bookName: 'Psalms', chapter: 2 },
    // Day 7: 2 Samuel 6, Psalm 132
    { bookName: '2 Samuel', chapter: 6 },
    { bookName: 'Psalms', chapter: 132 },
    // Day 8: 2 Samuel 7, Psalm 89
    { bookName: '2 Samuel', chapter: 7 },
    { bookName: 'Psalms', chapter: 89 },
    // Day 9: 2 Samuel 11, Psalm 51
    { bookName: '2 Samuel', chapter: 11 },
    { bookName: 'Psalms', chapter: 51 },
    // Day 10: 2 Samuel 12, Psalm 32
    { bookName: '2 Samuel', chapter: 12 },
    { bookName: 'Psalms', chapter: 32 },
    // Day 11: Psalm 23, Psalm 63
    { bookName: 'Psalms', chapter: 23 },
    { bookName: 'Psalms', chapter: 63 },
    // Day 12: 2 Samuel 15, Psalm 3
    { bookName: '2 Samuel', chapter: 15 },
    { bookName: 'Psalms', chapter: 3 },
    // Day 13: 1 Kings 2, Psalm 72
    { bookName: '1 Kings', chapter: 2 },
    { bookName: 'Psalms', chapter: 72 },
    // Day 14: Acts 13, Psalm 16
    { bookName: 'Acts', chapter: 13 },
    { bookName: 'Psalms', chapter: 16 },
  ],
  HEART_OF_GOD: [
    // Day 1: Exodus 34, Psalm 103
    { bookName: 'Exodus', chapter: 34 },
    { bookName: 'Psalms', chapter: 103 },
    // Day 2: Psalm 145, Psalm 146
    { bookName: 'Psalms', chapter: 145 },
    { bookName: 'Psalms', chapter: 146 },
    // Day 3: Isaiah 6, Isaiah 55
    { bookName: 'Isaiah', chapter: 6 },
    { bookName: 'Isaiah', chapter: 55 },
    // Day 4: Micah 6, Psalm 15
    { bookName: 'Micah', chapter: 6 },
    { bookName: 'Psalms', chapter: 15 },
    // Day 5: Matthew 5, Matthew 6
    { bookName: 'Matthew', chapter: 5 },
    { bookName: 'Matthew', chapter: 6 },
    // Day 6: Matthew 11, Matthew 22
    { bookName: 'Matthew', chapter: 11 },
    { bookName: 'Matthew', chapter: 22 },
    // Day 7: Luke 15, Luke 19
    { bookName: 'Luke', chapter: 15 },
    { bookName: 'Luke', chapter: 19 },
    // Day 8: John 1, John 3
    { bookName: 'John', chapter: 1 },
    { bookName: 'John', chapter: 3 },
    // Day 9: John 13, John 17
    { bookName: 'John', chapter: 13 },
    { bookName: 'John', chapter: 17 },
    // Day 10: Romans 5, Romans 8
    { bookName: 'Romans', chapter: 5 },
    { bookName: 'Romans', chapter: 8 },
    // Day 11: Ephesians 1, Ephesians 2
    { bookName: 'Ephesians', chapter: 1 },
    { bookName: 'Ephesians', chapter: 2 },
    // Day 12: Colossians 1, Colossians 3
    { bookName: 'Colossians', chapter: 1 },
    { bookName: 'Colossians', chapter: 3 },
    // Day 13: Hebrews 4, Hebrews 12
    { bookName: 'Hebrews', chapter: 4 },
    { bookName: 'Hebrews', chapter: 12 },
    // Day 14: 1 John 1, 1 John 4
    { bookName: '1 John', chapter: 1 },
    { bookName: '1 John', chapter: 4 },
    // Day 15: Psalm 51, Psalm 139
    { bookName: 'Psalms', chapter: 51 },
    { bookName: 'Psalms', chapter: 139 },
    // Day 16: Ezekiel 18, Ezekiel 36
    { bookName: 'Ezekiel', chapter: 18 },
    { bookName: 'Ezekiel', chapter: 36 },
    // Day 17: Jeremiah 9, Jeremiah 31
    { bookName: 'Jeremiah', chapter: 9 },
    { bookName: 'Jeremiah', chapter: 31 },
    // Day 18: Revelation 4, Revelation 5
    { bookName: 'Revelation', chapter: 4 },
    { bookName: 'Revelation', chapter: 5 },
    // Day 19: Revelation 19, Revelation 21
    { bookName: 'Revelation', chapter: 19 },
    { bookName: 'Revelation', chapter: 21 },
    // Day 20: Psalm 73, Psalm 84
    { bookName: 'Psalms', chapter: 73 },
    { bookName: 'Psalms', chapter: 84 },
    // Day 21: Psalm 115, Psalm 118
    { bookName: 'Psalms', chapter: 115 },
    { bookName: 'Psalms', chapter: 118 },
  ],
  CHRONOLOGICAL_BIBLE: [
    // Creation through Job (Days 1-45)
    { bookName: 'Genesis', chapter: 1 }, { bookName: 'Genesis', chapter: 2 }, { bookName: 'Genesis', chapter: 3 },
    { bookName: 'Genesis', chapter: 4 }, { bookName: 'Genesis', chapter: 5 }, { bookName: 'Genesis', chapter: 6 },
    { bookName: 'Genesis', chapter: 7 }, { bookName: 'Genesis', chapter: 8 }, { bookName: 'Genesis', chapter: 9 },
    { bookName: 'Genesis', chapter: 10 }, { bookName: 'Genesis', chapter: 11 },
    { bookName: 'Job', chapter: 1 }, { bookName: 'Job', chapter: 2 }, { bookName: 'Job', chapter: 3 },
    { bookName: 'Job', chapter: 4 }, { bookName: 'Job', chapter: 5 }, { bookName: 'Job', chapter: 6 },
    { bookName: 'Job', chapter: 7 }, { bookName: 'Job', chapter: 8 }, { bookName: 'Job', chapter: 9 },
    { bookName: 'Job', chapter: 10 }, { bookName: 'Job', chapter: 11 }, { bookName: 'Job', chapter: 12 },
    { bookName: 'Job', chapter: 13 }, { bookName: 'Job', chapter: 14 }, { bookName: 'Job', chapter: 15 },
    { bookName: 'Job', chapter: 16 }, { bookName: 'Job', chapter: 17 }, { bookName: 'Job', chapter: 18 },
    { bookName: 'Job', chapter: 19 }, { bookName: 'Job', chapter: 20 }, { bookName: 'Job', chapter: 21 },
    { bookName: 'Job', chapter: 22 }, { bookName: 'Job', chapter: 23 }, { bookName: 'Job', chapter: 24 },
    { bookName: 'Job', chapter: 25 }, { bookName: 'Job', chapter: 26 }, { bookName: 'Job', chapter: 27 },
    { bookName: 'Job', chapter: 28 }, { bookName: 'Job', chapter: 29 }, { bookName: 'Job', chapter: 30 },
    { bookName: 'Job', chapter: 31 }, { bookName: 'Job', chapter: 32 }, { bookName: 'Job', chapter: 33 },
    { bookName: 'Job', chapter: 34 }, { bookName: 'Job', chapter: 35 }, { bookName: 'Job', chapter: 36 },
    { bookName: 'Job', chapter: 37 }, { bookName: 'Job', chapter: 38 }, { bookName: 'Job', chapter: 39 },
    { bookName: 'Job', chapter: 40 }, { bookName: 'Job', chapter: 41 }, { bookName: 'Job', chapter: 42 },
    { bookName: 'Genesis', chapter: 12 }, { bookName: 'Genesis', chapter: 13 }, { bookName: 'Genesis', chapter: 14 },
    { bookName: 'Genesis', chapter: 15 }, { bookName: 'Genesis', chapter: 16 }, { bookName: 'Genesis', chapter: 17 },
    { bookName: 'Genesis', chapter: 18 }, { bookName: 'Genesis', chapter: 19 }, { bookName: 'Genesis', chapter: 20 },
    { bookName: 'Genesis', chapter: 21 }, { bookName: 'Genesis', chapter: 22 }, { bookName: 'Genesis', chapter: 23 },
    { bookName: 'Genesis', chapter: 24 }, { bookName: 'Genesis', chapter: 25 }, { bookName: 'Genesis', chapter: 26 },
    { bookName: 'Genesis', chapter: 27 }, { bookName: 'Genesis', chapter: 28 }, { bookName: 'Genesis', chapter: 29 },
    { bookName: 'Genesis', chapter: 30 }, { bookName: 'Genesis', chapter: 31 }, { bookName: 'Genesis', chapter: 32 },
    { bookName: 'Genesis', chapter: 33 }, { bookName: 'Genesis', chapter: 34 }, { bookName: 'Genesis', chapter: 35 },
    { bookName: 'Genesis', chapter: 36 }, { bookName: 'Genesis', chapter: 37 }, { bookName: 'Genesis', chapter: 38 },
    { bookName: 'Genesis', chapter: 39 }, { bookName: 'Genesis', chapter: 40 }, { bookName: 'Genesis', chapter: 41 },
    { bookName: 'Genesis', chapter: 42 }, { bookName: 'Genesis', chapter: 43 }, { bookName: 'Genesis', chapter: 44 },
    { bookName: 'Genesis', chapter: 45 }, { bookName: 'Genesis', chapter: 46 }, { bookName: 'Genesis', chapter: 47 },
    { bookName: 'Genesis', chapter: 48 }, { bookName: 'Genesis', chapter: 49 }, { bookName: 'Genesis', chapter: 50 },
    // Exodus through Deuteronomy
    { bookName: 'Exodus', chapter: 1 }, { bookName: 'Exodus', chapter: 2 }, { bookName: 'Exodus', chapter: 3 },
    { bookName: 'Exodus', chapter: 4 }, { bookName: 'Exodus', chapter: 5 }, { bookName: 'Exodus', chapter: 6 },
    { bookName: 'Exodus', chapter: 7 }, { bookName: 'Exodus', chapter: 8 }, { bookName: 'Exodus', chapter: 9 },
    { bookName: 'Exodus', chapter: 10 }, { bookName: 'Exodus', chapter: 11 }, { bookName: 'Exodus', chapter: 12 },
    { bookName: 'Exodus', chapter: 13 }, { bookName: 'Exodus', chapter: 14 }, { bookName: 'Exodus', chapter: 15 },
    { bookName: 'Exodus', chapter: 16 }, { bookName: 'Exodus', chapter: 17 }, { bookName: 'Exodus', chapter: 18 },
    { bookName: 'Exodus', chapter: 19 }, { bookName: 'Exodus', chapter: 20 }, { bookName: 'Exodus', chapter: 21 },
    { bookName: 'Exodus', chapter: 22 }, { bookName: 'Exodus', chapter: 23 }, { bookName: 'Exodus', chapter: 24 },
    { bookName: 'Exodus', chapter: 25 }, { bookName: 'Exodus', chapter: 26 }, { bookName: 'Exodus', chapter: 27 },
    { bookName: 'Exodus', chapter: 28 }, { bookName: 'Exodus', chapter: 29 }, { bookName: 'Exodus', chapter: 30 },
    { bookName: 'Exodus', chapter: 31 }, { bookName: 'Exodus', chapter: 32 }, { bookName: 'Exodus', chapter: 33 },
    { bookName: 'Exodus', chapter: 34 }, { bookName: 'Exodus', chapter: 35 }, { bookName: 'Exodus', chapter: 36 },
    { bookName: 'Exodus', chapter: 37 }, { bookName: 'Exodus', chapter: 38 }, { bookName: 'Exodus', chapter: 39 },
    { bookName: 'Exodus', chapter: 40 },
    { bookName: 'Leviticus', chapter: 1 }, { bookName: 'Leviticus', chapter: 2 }, { bookName: 'Leviticus', chapter: 3 },
    { bookName: 'Leviticus', chapter: 4 }, { bookName: 'Leviticus', chapter: 5 }, { bookName: 'Leviticus', chapter: 6 },
    { bookName: 'Leviticus', chapter: 7 }, { bookName: 'Leviticus', chapter: 8 }, { bookName: 'Leviticus', chapter: 9 },
    { bookName: 'Leviticus', chapter: 10 }, { bookName: 'Leviticus', chapter: 11 }, { bookName: 'Leviticus', chapter: 12 },
    { bookName: 'Leviticus', chapter: 13 }, { bookName: 'Leviticus', chapter: 14 }, { bookName: 'Leviticus', chapter: 15 },
    { bookName: 'Leviticus', chapter: 16 }, { bookName: 'Leviticus', chapter: 17 }, { bookName: 'Leviticus', chapter: 18 },
    { bookName: 'Leviticus', chapter: 19 }, { bookName: 'Leviticus', chapter: 20 }, { bookName: 'Leviticus', chapter: 21 },
    { bookName: 'Leviticus', chapter: 22 }, { bookName: 'Leviticus', chapter: 23 }, { bookName: 'Leviticus', chapter: 24 },
    { bookName: 'Leviticus', chapter: 25 }, { bookName: 'Leviticus', chapter: 26 }, { bookName: 'Leviticus', chapter: 27 },
    { bookName: 'Numbers', chapter: 1 }, { bookName: 'Numbers', chapter: 2 }, { bookName: 'Numbers', chapter: 3 },
    { bookName: 'Numbers', chapter: 4 }, { bookName: 'Numbers', chapter: 5 }, { bookName: 'Numbers', chapter: 6 },
    { bookName: 'Numbers', chapter: 7 }, { bookName: 'Numbers', chapter: 8 }, { bookName: 'Numbers', chapter: 9 },
    { bookName: 'Numbers', chapter: 10 }, { bookName: 'Numbers', chapter: 11 }, { bookName: 'Numbers', chapter: 12 },
    { bookName: 'Numbers', chapter: 13 }, { bookName: 'Numbers', chapter: 14 }, { bookName: 'Numbers', chapter: 15 },
    { bookName: 'Numbers', chapter: 16 }, { bookName: 'Numbers', chapter: 17 }, { bookName: 'Numbers', chapter: 18 },
    { bookName: 'Numbers', chapter: 19 }, { bookName: 'Numbers', chapter: 20 }, { bookName: 'Numbers', chapter: 21 },
    { bookName: 'Numbers', chapter: 22 }, { bookName: 'Numbers', chapter: 23 }, { bookName: 'Numbers', chapter: 24 },
    { bookName: 'Numbers', chapter: 25 }, { bookName: 'Numbers', chapter: 26 }, { bookName: 'Numbers', chapter: 27 },
    { bookName: 'Numbers', chapter: 28 }, { bookName: 'Numbers', chapter: 29 }, { bookName: 'Numbers', chapter: 30 },
    { bookName: 'Numbers', chapter: 31 }, { bookName: 'Numbers', chapter: 32 }, { bookName: 'Numbers', chapter: 33 },
    { bookName: 'Numbers', chapter: 34 }, { bookName: 'Numbers', chapter: 35 }, { bookName: 'Numbers', chapter: 36 },
    { bookName: 'Deuteronomy', chapter: 1 }, { bookName: 'Deuteronomy', chapter: 2 }, { bookName: 'Deuteronomy', chapter: 3 },
    { bookName: 'Deuteronomy', chapter: 4 }, { bookName: 'Deuteronomy', chapter: 5 }, { bookName: 'Deuteronomy', chapter: 6 },
    { bookName: 'Deuteronomy', chapter: 7 }, { bookName: 'Deuteronomy', chapter: 8 }, { bookName: 'Deuteronomy', chapter: 9 },
    { bookName: 'Deuteronomy', chapter: 10 }, { bookName: 'Deuteronomy', chapter: 11 }, { bookName: 'Deuteronomy', chapter: 12 },
    { bookName: 'Deuteronomy', chapter: 13 }, { bookName: 'Deuteronomy', chapter: 14 }, { bookName: 'Deuteronomy', chapter: 15 },
    { bookName: 'Deuteronomy', chapter: 16 }, { bookName: 'Deuteronomy', chapter: 17 }, { bookName: 'Deuteronomy', chapter: 18 },
    { bookName: 'Deuteronomy', chapter: 19 }, { bookName: 'Deuteronomy', chapter: 20 }, { bookName: 'Deuteronomy', chapter: 21 },
    { bookName: 'Deuteronomy', chapter: 22 }, { bookName: 'Deuteronomy', chapter: 23 }, { bookName: 'Deuteronomy', chapter: 24 },
    { bookName: 'Deuteronomy', chapter: 25 }, { bookName: 'Deuteronomy', chapter: 26 }, { bookName: 'Deuteronomy', chapter: 27 },
    { bookName: 'Deuteronomy', chapter: 28 }, { bookName: 'Deuteronomy', chapter: 29 }, { bookName: 'Deuteronomy', chapter: 30 },
    { bookName: 'Deuteronomy', chapter: 31 }, { bookName: 'Deuteronomy', chapter: 32 }, { bookName: 'Deuteronomy', chapter: 33 },
    { bookName: 'Deuteronomy', chapter: 34 },
    // Joshua, Judges, Ruth
    { bookName: 'Joshua', chapter: 1 }, { bookName: 'Joshua', chapter: 2 }, { bookName: 'Joshua', chapter: 3 },
    { bookName: 'Joshua', chapter: 4 }, { bookName: 'Joshua', chapter: 5 }, { bookName: 'Joshua', chapter: 6 },
    { bookName: 'Joshua', chapter: 7 }, { bookName: 'Joshua', chapter: 8 }, { bookName: 'Joshua', chapter: 9 },
    { bookName: 'Joshua', chapter: 10 }, { bookName: 'Joshua', chapter: 11 }, { bookName: 'Joshua', chapter: 12 },
    { bookName: 'Joshua', chapter: 13 }, { bookName: 'Joshua', chapter: 14 }, { bookName: 'Joshua', chapter: 15 },
    { bookName: 'Joshua', chapter: 16 }, { bookName: 'Joshua', chapter: 17 }, { bookName: 'Joshua', chapter: 18 },
    { bookName: 'Joshua', chapter: 19 }, { bookName: 'Joshua', chapter: 20 }, { bookName: 'Joshua', chapter: 21 },
    { bookName: 'Joshua', chapter: 22 }, { bookName: 'Joshua', chapter: 23 }, { bookName: 'Joshua', chapter: 24 },
    { bookName: 'Judges', chapter: 1 }, { bookName: 'Judges', chapter: 2 }, { bookName: 'Judges', chapter: 3 },
    { bookName: 'Judges', chapter: 4 }, { bookName: 'Judges', chapter: 5 }, { bookName: 'Judges', chapter: 6 },
    { bookName: 'Judges', chapter: 7 }, { bookName: 'Judges', chapter: 8 }, { bookName: 'Judges', chapter: 9 },
    { bookName: 'Judges', chapter: 10 }, { bookName: 'Judges', chapter: 11 }, { bookName: 'Judges', chapter: 12 },
    { bookName: 'Judges', chapter: 13 }, { bookName: 'Judges', chapter: 14 }, { bookName: 'Judges', chapter: 15 },
    { bookName: 'Judges', chapter: 16 }, { bookName: 'Judges', chapter: 17 }, { bookName: 'Judges', chapter: 18 },
    { bookName: 'Judges', chapter: 19 }, { bookName: 'Judges', chapter: 20 }, { bookName: 'Judges', chapter: 21 },
    { bookName: 'Ruth', chapter: 1 }, { bookName: 'Ruth', chapter: 2 }, { bookName: 'Ruth', chapter: 3 },
    { bookName: 'Ruth', chapter: 4 },
    // 1 & 2 Samuel
    { bookName: '1 Samuel', chapter: 1 }, { bookName: '1 Samuel', chapter: 2 }, { bookName: '1 Samuel', chapter: 3 },
    { bookName: '1 Samuel', chapter: 4 }, { bookName: '1 Samuel', chapter: 5 }, { bookName: '1 Samuel', chapter: 6 },
    { bookName: '1 Samuel', chapter: 7 }, { bookName: '1 Samuel', chapter: 8 }, { bookName: '1 Samuel', chapter: 9 },
    { bookName: '1 Samuel', chapter: 10 }, { bookName: '1 Samuel', chapter: 11 }, { bookName: '1 Samuel', chapter: 12 },
    { bookName: '1 Samuel', chapter: 13 }, { bookName: '1 Samuel', chapter: 14 }, { bookName: '1 Samuel', chapter: 15 },
    { bookName: '1 Samuel', chapter: 16 }, { bookName: '1 Samuel', chapter: 17 }, { bookName: '1 Samuel', chapter: 18 },
    { bookName: '1 Samuel', chapter: 19 }, { bookName: '1 Samuel', chapter: 20 }, { bookName: '1 Samuel', chapter: 21 },
    { bookName: '1 Samuel', chapter: 22 }, { bookName: '1 Samuel', chapter: 23 }, { bookName: '1 Samuel', chapter: 24 },
    { bookName: '1 Samuel', chapter: 25 }, { bookName: '1 Samuel', chapter: 26 }, { bookName: '1 Samuel', chapter: 27 },
    { bookName: '1 Samuel', chapter: 28 }, { bookName: '1 Samuel', chapter: 29 }, { bookName: '1 Samuel', chapter: 30 },
    { bookName: '1 Samuel', chapter: 31 },
    { bookName: '2 Samuel', chapter: 1 }, { bookName: '2 Samuel', chapter: 2 }, { bookName: '2 Samuel', chapter: 3 },
    { bookName: '2 Samuel', chapter: 4 }, { bookName: '2 Samuel', chapter: 5 },
    { bookName: '1 Chronicles', chapter: 1 }, { bookName: '1 Chronicles', chapter: 2 }, { bookName: '1 Chronicles', chapter: 3 },
    { bookName: '1 Chronicles', chapter: 4 }, { bookName: '1 Chronicles', chapter: 5 }, { bookName: '1 Chronicles', chapter: 6 },
    { bookName: '1 Chronicles', chapter: 7 }, { bookName: '1 Chronicles', chapter: 8 }, { bookName: '1 Chronicles', chapter: 9 },
    { bookName: '1 Chronicles', chapter: 10 }, { bookName: '1 Chronicles', chapter: 11 }, { bookName: '1 Chronicles', chapter: 12 },
    { bookName: '2 Samuel', chapter: 6 }, { bookName: '2 Samuel', chapter: 7 }, { bookName: '2 Samuel', chapter: 8 },
    { bookName: '2 Samuel', chapter: 9 }, { bookName: '2 Samuel', chapter: 10 },
    { bookName: '1 Chronicles', chapter: 13 }, { bookName: '1 Chronicles', chapter: 14 }, { bookName: '1 Chronicles', chapter: 15 },
    { bookName: '1 Chronicles', chapter: 16 }, { bookName: '1 Chronicles', chapter: 17 }, { bookName: '1 Chronicles', chapter: 18 },
    { bookName: '1 Chronicles', chapter: 19 }, { bookName: '1 Chronicles', chapter: 20 },
    { bookName: '2 Samuel', chapter: 11 }, { bookName: '2 Samuel', chapter: 12 }, { bookName: '2 Samuel', chapter: 13 },
    { bookName: '2 Samuel', chapter: 14 }, { bookName: '2 Samuel', chapter: 15 }, { bookName: '2 Samuel', chapter: 16 },
    { bookName: '2 Samuel', chapter: 17 }, { bookName: '2 Samuel', chapter: 18 }, { bookName: '2 Samuel', chapter: 19 },
    { bookName: '2 Samuel', chapter: 20 }, { bookName: '2 Samuel', chapter: 21 }, { bookName: '2 Samuel', chapter: 22 },
    { bookName: '2 Samuel', chapter: 23 }, { bookName: '2 Samuel', chapter: 24 },
    { bookName: '1 Chronicles', chapter: 21 }, { bookName: '1 Chronicles', chapter: 22 }, { bookName: '1 Chronicles', chapter: 23 },
    { bookName: '1 Chronicles', chapter: 24 }, { bookName: '1 Chronicles', chapter: 25 }, { bookName: '1 Chronicles', chapter: 26 },
    { bookName: '1 Chronicles', chapter: 27 }, { bookName: '1 Chronicles', chapter: 28 }, { bookName: '1 Chronicles', chapter: 29 },
    // Psalms (selected David's era)
    { bookName: 'Psalms', chapter: 1 }, { bookName: 'Psalms', chapter: 2 }, { bookName: 'Psalms', chapter: 3 },
    { bookName: 'Psalms', chapter: 8 }, { bookName: 'Psalms', chapter: 11 }, { bookName: 'Psalms', chapter: 15 },
    { bookName: 'Psalms', chapter: 16 }, { bookName: 'Psalms', chapter: 18 }, { bookName: 'Psalms', chapter: 19 },
    { bookName: 'Psalms', chapter: 22 }, { bookName: 'Psalms', chapter: 23 }, { bookName: 'Psalms', chapter: 24 },
    { bookName: 'Psalms', chapter: 27 }, { bookName: 'Psalms', chapter: 32 }, { bookName: 'Psalms', chapter: 34 },
    { bookName: 'Psalms', chapter: 37 }, { bookName: 'Psalms', chapter: 40 }, { bookName: 'Psalms', chapter: 41 },
    { bookName: 'Psalms', chapter: 51 }, { bookName: 'Psalms', chapter: 57 }, { bookName: 'Psalms', chapter: 59 },
    { bookName: 'Psalms', chapter: 63 }, { bookName: 'Psalms', chapter: 72 },
    // 1 & 2 Kings, 2 Chronicles (Solomon & Kingdom Era)
    { bookName: '1 Kings', chapter: 1 }, { bookName: '1 Kings', chapter: 2 },
    { bookName: '2 Chronicles', chapter: 1 },
    { bookName: '1 Kings', chapter: 3 }, { bookName: '1 Kings', chapter: 4 }, { bookName: '1 Kings', chapter: 5 },
    { bookName: '1 Kings', chapter: 6 }, { bookName: '1 Kings', chapter: 7 },
    { bookName: '2 Chronicles', chapter: 2 }, { bookName: '2 Chronicles', chapter: 3 }, { bookName: '2 Chronicles', chapter: 4 },
    { bookName: '2 Chronicles', chapter: 5 },
    { bookName: '1 Kings', chapter: 8 },
    { bookName: '2 Chronicles', chapter: 6 }, { bookName: '2 Chronicles', chapter: 7 },
    { bookName: '1 Kings', chapter: 9 }, { bookName: '1 Kings', chapter: 10 },
    { bookName: '2 Chronicles', chapter: 8 }, { bookName: '2 Chronicles', chapter: 9 },
    { bookName: 'Proverbs', chapter: 1 }, { bookName: 'Proverbs', chapter: 2 }, { bookName: 'Proverbs', chapter: 3 },
    { bookName: 'Proverbs', chapter: 4 }, { bookName: 'Proverbs', chapter: 5 }, { bookName: 'Proverbs', chapter: 6 },
    { bookName: 'Proverbs', chapter: 7 }, { bookName: 'Proverbs', chapter: 8 }, { bookName: 'Proverbs', chapter: 9 },
    { bookName: 'Proverbs', chapter: 10 }, { bookName: 'Proverbs', chapter: 11 }, { bookName: 'Proverbs', chapter: 12 },
    { bookName: 'Proverbs', chapter: 13 }, { bookName: 'Proverbs', chapter: 14 }, { bookName: 'Proverbs', chapter: 15 },
    { bookName: 'Proverbs', chapter: 16 }, { bookName: 'Proverbs', chapter: 17 }, { bookName: 'Proverbs', chapter: 18 },
    { bookName: 'Proverbs', chapter: 19 }, { bookName: 'Proverbs', chapter: 20 }, { bookName: 'Proverbs', chapter: 21 },
    { bookName: 'Proverbs', chapter: 22 }, { bookName: 'Proverbs', chapter: 23 }, { bookName: 'Proverbs', chapter: 24 },
    { bookName: 'Proverbs', chapter: 25 }, { bookName: 'Proverbs', chapter: 26 }, { bookName: 'Proverbs', chapter: 27 },
    { bookName: 'Proverbs', chapter: 28 }, { bookName: 'Proverbs', chapter: 29 }, { bookName: 'Proverbs', chapter: 30 },
    { bookName: 'Proverbs', chapter: 31 },
    { bookName: 'Ecclesiastes', chapter: 1 }, { bookName: 'Ecclesiastes', chapter: 2 }, { bookName: 'Ecclesiastes', chapter: 3 },
    { bookName: 'Ecclesiastes', chapter: 4 }, { bookName: 'Ecclesiastes', chapter: 5 }, { bookName: 'Ecclesiastes', chapter: 6 },
    { bookName: 'Ecclesiastes', chapter: 7 }, { bookName: 'Ecclesiastes', chapter: 8 }, { bookName: 'Ecclesiastes', chapter: 9 },
    { bookName: 'Ecclesiastes', chapter: 10 }, { bookName: 'Ecclesiastes', chapter: 11 }, { bookName: 'Ecclesiastes', chapter: 12 },
    { bookName: 'Song of Solomon', chapter: 1 }, { bookName: 'Song of Solomon', chapter: 2 }, { bookName: 'Song of Solomon', chapter: 3 },
    { bookName: 'Song of Solomon', chapter: 4 }, { bookName: 'Song of Solomon', chapter: 5 }, { bookName: 'Song of Solomon', chapter: 6 },
    { bookName: 'Song of Solomon', chapter: 7 }, { bookName: 'Song of Solomon', chapter: 8 },
    { bookName: '1 Kings', chapter: 11 },
    { bookName: '2 Chronicles', chapter: 10 },
    { bookName: '1 Kings', chapter: 12 }, { bookName: '1 Kings', chapter: 13 }, { bookName: '1 Kings', chapter: 14 },
    { bookName: '2 Chronicles', chapter: 11 }, { bookName: '2 Chronicles', chapter: 12 },
    { bookName: '1 Kings', chapter: 15 },
    { bookName: '2 Chronicles', chapter: 13 }, { bookName: '2 Chronicles', chapter: 14 }, { bookName: '2 Chronicles', chapter: 15 },
    { bookName: '2 Chronicles', chapter: 16 },
    { bookName: '1 Kings', chapter: 16 }, { bookName: '1 Kings', chapter: 17 }, { bookName: '1 Kings', chapter: 18 },
    { bookName: '1 Kings', chapter: 19 }, { bookName: '1 Kings', chapter: 20 }, { bookName: '1 Kings', chapter: 21 },
    { bookName: '1 Kings', chapter: 22 },
    { bookName: '2 Chronicles', chapter: 17 }, { bookName: '2 Chronicles', chapter: 18 }, { bookName: '2 Chronicles', chapter: 19 },
    { bookName: '2 Chronicles', chapter: 20 },
    { bookName: '2 Kings', chapter: 1 }, { bookName: '2 Kings', chapter: 2 }, { bookName: '2 Kings', chapter: 3 },
    { bookName: '2 Chronicles', chapter: 21 },
    { bookName: '2 Kings', chapter: 4 }, { bookName: '2 Kings', chapter: 5 }, { bookName: '2 Kings', chapter: 6 },
    { bookName: '2 Kings', chapter: 7 }, { bookName: '2 Kings', chapter: 8 },
    { bookName: '2 Chronicles', chapter: 22 }, { bookName: '2 Chronicles', chapter: 23 },
    { bookName: '2 Kings', chapter: 9 }, { bookName: '2 Kings', chapter: 10 }, { bookName: '2 Kings', chapter: 11 },
    { bookName: '2 Kings', chapter: 12 },
    { bookName: '2 Chronicles', chapter: 24 },
    { bookName: '2 Kings', chapter: 13 }, { bookName: '2 Kings', chapter: 14 },
    { bookName: '2 Chronicles', chapter: 25 },
    { bookName: 'Jonah', chapter: 1 }, { bookName: 'Jonah', chapter: 2 }, { bookName: 'Jonah', chapter: 3 },
    { bookName: 'Jonah', chapter: 4 },
    { bookName: 'Amos', chapter: 1 }, { bookName: 'Amos', chapter: 2 }, { bookName: 'Amos', chapter: 3 },
    { bookName: 'Amos', chapter: 4 }, { bookName: 'Amos', chapter: 5 }, { bookName: 'Amos', chapter: 6 },
    { bookName: 'Amos', chapter: 7 }, { bookName: 'Amos', chapter: 8 }, { bookName: 'Amos', chapter: 9 },
    { bookName: '2 Kings', chapter: 15 },
    { bookName: '2 Chronicles', chapter: 26 }, { bookName: '2 Chronicles', chapter: 27 },
    { bookName: 'Hosea', chapter: 1 }, { bookName: 'Hosea', chapter: 2 }, { bookName: 'Hosea', chapter: 3 },
    { bookName: 'Hosea', chapter: 4 }, { bookName: 'Hosea', chapter: 5 }, { bookName: 'Hosea', chapter: 6 },
    { bookName: 'Hosea', chapter: 7 }, { bookName: 'Hosea', chapter: 8 }, { bookName: 'Hosea', chapter: 9 },
    { bookName: 'Hosea', chapter: 10 }, { bookName: 'Hosea', chapter: 11 }, { bookName: 'Hosea', chapter: 12 },
    { bookName: 'Hosea', chapter: 13 }, { bookName: 'Hosea', chapter: 14 },
    { bookName: 'Isaiah', chapter: 1 }, { bookName: 'Isaiah', chapter: 2 }, { bookName: 'Isaiah', chapter: 3 },
    { bookName: 'Isaiah', chapter: 4 }, { bookName: 'Isaiah', chapter: 5 }, { bookName: 'Isaiah', chapter: 6 },
    { bookName: 'Isaiah', chapter: 7 }, { bookName: 'Isaiah', chapter: 8 }, { bookName: 'Isaiah', chapter: 9 },
    { bookName: 'Isaiah', chapter: 10 }, { bookName: 'Isaiah', chapter: 11 }, { bookName: 'Isaiah', chapter: 12 },
    { bookName: 'Isaiah', chapter: 13 }, { bookName: 'Isaiah', chapter: 14 }, { bookName: 'Isaiah', chapter: 15 },
    { bookName: 'Isaiah', chapter: 16 }, { bookName: 'Isaiah', chapter: 17 }, { bookName: 'Isaiah', chapter: 18 },
    { bookName: 'Isaiah', chapter: 19 }, { bookName: 'Isaiah', chapter: 20 }, { bookName: 'Isaiah', chapter: 21 },
    { bookName: 'Isaiah', chapter: 22 }, { bookName: 'Isaiah', chapter: 23 }, { bookName: 'Isaiah', chapter: 24 },
    { bookName: 'Isaiah', chapter: 25 }, { bookName: 'Isaiah', chapter: 26 }, { bookName: 'Isaiah', chapter: 27 },
    { bookName: 'Isaiah', chapter: 28 }, { bookName: 'Isaiah', chapter: 29 }, { bookName: 'Isaiah', chapter: 30 },
    { bookName: 'Isaiah', chapter: 31 }, { bookName: 'Isaiah', chapter: 32 }, { bookName: 'Isaiah', chapter: 33 },
    { bookName: 'Isaiah', chapter: 34 }, { bookName: 'Isaiah', chapter: 35 },
    { bookName: 'Micah', chapter: 1 }, { bookName: 'Micah', chapter: 2 }, { bookName: 'Micah', chapter: 3 },
    { bookName: 'Micah', chapter: 4 }, { bookName: 'Micah', chapter: 5 }, { bookName: 'Micah', chapter: 6 },
    { bookName: 'Micah', chapter: 7 },
    { bookName: '2 Kings', chapter: 16 },
    { bookName: '2 Chronicles', chapter: 28 },
    { bookName: '2 Kings', chapter: 17 }, { bookName: '2 Kings', chapter: 18 },
    { bookName: 'Isaiah', chapter: 36 }, { bookName: 'Isaiah', chapter: 37 }, { bookName: 'Isaiah', chapter: 38 },
    { bookName: 'Isaiah', chapter: 39 },
    { bookName: '2 Kings', chapter: 19 }, { bookName: '2 Kings', chapter: 20 },
    { bookName: '2 Chronicles', chapter: 29 }, { bookName: '2 Chronicles', chapter: 30 }, { bookName: '2 Chronicles', chapter: 31 },
    { bookName: '2 Chronicles', chapter: 32 },
    { bookName: 'Nahum', chapter: 1 }, { bookName: 'Nahum', chapter: 2 }, { bookName: 'Nahum', chapter: 3 },
    { bookName: '2 Kings', chapter: 21 },
    { bookName: '2 Chronicles', chapter: 33 },
    { bookName: 'Zephaniah', chapter: 1 }, { bookName: 'Zephaniah', chapter: 2 }, { bookName: 'Zephaniah', chapter: 3 },
    { bookName: 'Habakkuk', chapter: 1 }, { bookName: 'Habakkuk', chapter: 2 }, { bookName: 'Habakkuk', chapter: 3 },
    { bookName: '2 Kings', chapter: 22 }, { bookName: '2 Kings', chapter: 23 },
    { bookName: '2 Chronicles', chapter: 34 }, { bookName: '2 Chronicles', chapter: 35 },
    { bookName: 'Jeremiah', chapter: 1 }, { bookName: 'Jeremiah', chapter: 2 }, { bookName: 'Jeremiah', chapter: 3 },
    { bookName: 'Jeremiah', chapter: 4 }, { bookName: 'Jeremiah', chapter: 5 }, { bookName: 'Jeremiah', chapter: 6 },
    { bookName: 'Jeremiah', chapter: 7 }, { bookName: 'Jeremiah', chapter: 8 }, { bookName: 'Jeremiah', chapter: 9 },
    { bookName: 'Jeremiah', chapter: 10 }, { bookName: 'Jeremiah', chapter: 11 }, { bookName: 'Jeremiah', chapter: 12 },
    { bookName: 'Jeremiah', chapter: 13 }, { bookName: 'Jeremiah', chapter: 14 }, { bookName: 'Jeremiah', chapter: 15 },
    { bookName: 'Jeremiah', chapter: 16 }, { bookName: 'Jeremiah', chapter: 17 }, { bookName: 'Jeremiah', chapter: 18 },
    { bookName: 'Jeremiah', chapter: 19 }, { bookName: 'Jeremiah', chapter: 20 }, { bookName: 'Jeremiah', chapter: 21 },
    { bookName: 'Jeremiah', chapter: 22 }, { bookName: 'Jeremiah', chapter: 23 }, { bookName: 'Jeremiah', chapter: 24 },
    { bookName: 'Jeremiah', chapter: 25 }, { bookName: 'Jeremiah', chapter: 26 }, { bookName: 'Jeremiah', chapter: 27 },
    { bookName: 'Jeremiah', chapter: 28 }, { bookName: 'Jeremiah', chapter: 29 }, { bookName: 'Jeremiah', chapter: 30 },
    { bookName: 'Jeremiah', chapter: 31 }, { bookName: 'Jeremiah', chapter: 32 }, { bookName: 'Jeremiah', chapter: 33 },
    { bookName: 'Jeremiah', chapter: 34 }, { bookName: 'Jeremiah', chapter: 35 }, { bookName: 'Jeremiah', chapter: 36 },
    { bookName: 'Jeremiah', chapter: 37 }, { bookName: 'Jeremiah', chapter: 38 }, { bookName: 'Jeremiah', chapter: 39 },
    { bookName: 'Jeremiah', chapter: 40 }, { bookName: 'Jeremiah', chapter: 41 }, { bookName: 'Jeremiah', chapter: 42 },
    { bookName: 'Jeremiah', chapter: 43 }, { bookName: 'Jeremiah', chapter: 44 }, { bookName: 'Jeremiah', chapter: 45 },
    { bookName: 'Jeremiah', chapter: 46 }, { bookName: 'Jeremiah', chapter: 47 }, { bookName: 'Jeremiah', chapter: 48 },
    { bookName: 'Jeremiah', chapter: 49 }, { bookName: 'Jeremiah', chapter: 50 }, { bookName: 'Jeremiah', chapter: 51 },
    { bookName: 'Jeremiah', chapter: 52 },
    { bookName: '2 Kings', chapter: 24 }, { bookName: '2 Kings', chapter: 25 },
    { bookName: '2 Chronicles', chapter: 36 },
    { bookName: 'Lamentations', chapter: 1 }, { bookName: 'Lamentations', chapter: 2 }, { bookName: 'Lamentations', chapter: 3 },
    { bookName: 'Lamentations', chapter: 4 }, { bookName: 'Lamentations', chapter: 5 },
    { bookName: 'Obadiah', chapter: 1 },
    { bookName: 'Ezekiel', chapter: 1 }, { bookName: 'Ezekiel', chapter: 2 }, { bookName: 'Ezekiel', chapter: 3 },
    { bookName: 'Ezekiel', chapter: 4 }, { bookName: 'Ezekiel', chapter: 5 }, { bookName: 'Ezekiel', chapter: 6 },
    { bookName: 'Ezekiel', chapter: 7 }, { bookName: 'Ezekiel', chapter: 8 }, { bookName: 'Ezekiel', chapter: 9 },
    { bookName: 'Ezekiel', chapter: 10 }, { bookName: 'Ezekiel', chapter: 11 }, { bookName: 'Ezekiel', chapter: 12 },
    { bookName: 'Ezekiel', chapter: 13 }, { bookName: 'Ezekiel', chapter: 14 }, { bookName: 'Ezekiel', chapter: 15 },
    { bookName: 'Ezekiel', chapter: 16 }, { bookName: 'Ezekiel', chapter: 17 }, { bookName: 'Ezekiel', chapter: 18 },
    { bookName: 'Ezekiel', chapter: 19 }, { bookName: 'Ezekiel', chapter: 20 }, { bookName: 'Ezekiel', chapter: 21 },
    { bookName: 'Ezekiel', chapter: 22 }, { bookName: 'Ezekiel', chapter: 23 }, { bookName: 'Ezekiel', chapter: 24 },
    { bookName: 'Ezekiel', chapter: 25 }, { bookName: 'Ezekiel', chapter: 26 }, { bookName: 'Ezekiel', chapter: 27 },
    { bookName: 'Ezekiel', chapter: 28 }, { bookName: 'Ezekiel', chapter: 29 }, { bookName: 'Ezekiel', chapter: 30 },
    { bookName: 'Ezekiel', chapter: 31 }, { bookName: 'Ezekiel', chapter: 32 }, { bookName: 'Ezekiel', chapter: 33 },
    { bookName: 'Ezekiel', chapter: 34 }, { bookName: 'Ezekiel', chapter: 35 }, { bookName: 'Ezekiel', chapter: 36 },
    { bookName: 'Ezekiel', chapter: 37 }, { bookName: 'Ezekiel', chapter: 38 }, { bookName: 'Ezekiel', chapter: 39 },
    { bookName: 'Ezekiel', chapter: 40 }, { bookName: 'Ezekiel', chapter: 41 }, { bookName: 'Ezekiel', chapter: 42 },
    { bookName: 'Ezekiel', chapter: 43 }, { bookName: 'Ezekiel', chapter: 44 }, { bookName: 'Ezekiel', chapter: 45 },
    { bookName: 'Ezekiel', chapter: 46 }, { bookName: 'Ezekiel', chapter: 47 }, { bookName: 'Ezekiel', chapter: 48 },
    { bookName: 'Daniel', chapter: 1 }, { bookName: 'Daniel', chapter: 2 }, { bookName: 'Daniel', chapter: 3 },
    { bookName: 'Daniel', chapter: 4 }, { bookName: 'Daniel', chapter: 5 }, { bookName: 'Daniel', chapter: 6 },
    { bookName: 'Daniel', chapter: 7 }, { bookName: 'Daniel', chapter: 8 }, { bookName: 'Daniel', chapter: 9 },
    { bookName: 'Daniel', chapter: 10 }, { bookName: 'Daniel', chapter: 11 }, { bookName: 'Daniel', chapter: 12 },
    { bookName: 'Ezra', chapter: 1 }, { bookName: 'Ezra', chapter: 2 }, { bookName: 'Ezra', chapter: 3 },
    { bookName: 'Ezra', chapter: 4 }, { bookName: 'Ezra', chapter: 5 }, { bookName: 'Ezra', chapter: 6 },
    { bookName: 'Haggai', chapter: 1 }, { bookName: 'Haggai', chapter: 2 },
    { bookName: 'Zechariah', chapter: 1 }, { bookName: 'Zechariah', chapter: 2 }, { bookName: 'Zechariah', chapter: 3 },
    { bookName: 'Zechariah', chapter: 4 }, { bookName: 'Zechariah', chapter: 5 }, { bookName: 'Zechariah', chapter: 6 },
    { bookName: 'Zechariah', chapter: 7 }, { bookName: 'Zechariah', chapter: 8 }, { bookName: 'Zechariah', chapter: 9 },
    { bookName: 'Zechariah', chapter: 10 }, { bookName: 'Zechariah', chapter: 11 }, { bookName: 'Zechariah', chapter: 12 },
    { bookName: 'Zechariah', chapter: 13 }, { bookName: 'Zechariah', chapter: 14 },
    { bookName: 'Esther', chapter: 1 }, { bookName: 'Esther', chapter: 2 }, { bookName: 'Esther', chapter: 3 },
    { bookName: 'Esther', chapter: 4 }, { bookName: 'Esther', chapter: 5 }, { bookName: 'Esther', chapter: 6 },
    { bookName: 'Esther', chapter: 7 }, { bookName: 'Esther', chapter: 8 }, { bookName: 'Esther', chapter: 9 },
    { bookName: 'Esther', chapter: 10 },
    { bookName: 'Ezra', chapter: 7 }, { bookName: 'Ezra', chapter: 8 }, { bookName: 'Ezra', chapter: 9 },
    { bookName: 'Ezra', chapter: 10 },
    { bookName: 'Nehemiah', chapter: 1 }, { bookName: 'Nehemiah', chapter: 2 }, { bookName: 'Nehemiah', chapter: 3 },
    { bookName: 'Nehemiah', chapter: 4 }, { bookName: 'Nehemiah', chapter: 5 }, { bookName: 'Nehemiah', chapter: 6 },
    { bookName: 'Nehemiah', chapter: 7 }, { bookName: 'Nehemiah', chapter: 8 }, { bookName: 'Nehemiah', chapter: 9 },
    { bookName: 'Nehemiah', chapter: 10 }, { bookName: 'Nehemiah', chapter: 11 }, { bookName: 'Nehemiah', chapter: 12 },
    { bookName: 'Nehemiah', chapter: 13 },
    { bookName: 'Malachi', chapter: 1 }, { bookName: 'Malachi', chapter: 2 }, { bookName: 'Malachi', chapter: 3 },
    { bookName: 'Malachi', chapter: 4 },
    { bookName: 'Isaiah', chapter: 40 }, { bookName: 'Isaiah', chapter: 41 }, { bookName: 'Isaiah', chapter: 42 },
    { bookName: 'Isaiah', chapter: 43 }, { bookName: 'Isaiah', chapter: 44 }, { bookName: 'Isaiah', chapter: 45 },
    { bookName: 'Isaiah', chapter: 46 }, { bookName: 'Isaiah', chapter: 47 }, { bookName: 'Isaiah', chapter: 48 },
    { bookName: 'Isaiah', chapter: 49 }, { bookName: 'Isaiah', chapter: 50 }, { bookName: 'Isaiah', chapter: 51 },
    { bookName: 'Isaiah', chapter: 52 }, { bookName: 'Isaiah', chapter: 53 }, { bookName: 'Isaiah', chapter: 54 },
    { bookName: 'Isaiah', chapter: 55 }, { bookName: 'Isaiah', chapter: 56 }, { bookName: 'Isaiah', chapter: 57 },
    { bookName: 'Isaiah', chapter: 58 }, { bookName: 'Isaiah', chapter: 59 }, { bookName: 'Isaiah', chapter: 60 },
    { bookName: 'Isaiah', chapter: 61 }, { bookName: 'Isaiah', chapter: 62 }, { bookName: 'Isaiah', chapter: 63 },
    { bookName: 'Isaiah', chapter: 64 }, { bookName: 'Isaiah', chapter: 65 }, { bookName: 'Isaiah', chapter: 66 },
    { bookName: 'Joel', chapter: 1 }, { bookName: 'Joel', chapter: 2 }, { bookName: 'Joel', chapter: 3 },
    // More Psalms (various eras)
    { bookName: 'Psalms', chapter: 42 }, { bookName: 'Psalms', chapter: 43 }, { bookName: 'Psalms', chapter: 45 },
    { bookName: 'Psalms', chapter: 46 }, { bookName: 'Psalms', chapter: 47 }, { bookName: 'Psalms', chapter: 48 },
    { bookName: 'Psalms', chapter: 49 }, { bookName: 'Psalms', chapter: 50 }, { bookName: 'Psalms', chapter: 65 },
    { bookName: 'Psalms', chapter: 66 }, { bookName: 'Psalms', chapter: 67 }, { bookName: 'Psalms', chapter: 68 },
    { bookName: 'Psalms', chapter: 73 }, { bookName: 'Psalms', chapter: 84 }, { bookName: 'Psalms', chapter: 85 },
    { bookName: 'Psalms', chapter: 87 }, { bookName: 'Psalms', chapter: 89 }, { bookName: 'Psalms', chapter: 90 },
    { bookName: 'Psalms', chapter: 91 }, { bookName: 'Psalms', chapter: 95 }, { bookName: 'Psalms', chapter: 96 },
    { bookName: 'Psalms', chapter: 97 }, { bookName: 'Psalms', chapter: 98 }, { bookName: 'Psalms', chapter: 99 },
    { bookName: 'Psalms', chapter: 100 }, { bookName: 'Psalms', chapter: 103 }, { bookName: 'Psalms', chapter: 107 },
    { bookName: 'Psalms', chapter: 110 }, { bookName: 'Psalms', chapter: 111 }, { bookName: 'Psalms', chapter: 112 },
    { bookName: 'Psalms', chapter: 113 }, { bookName: 'Psalms', chapter: 114 }, { bookName: 'Psalms', chapter: 115 },
    { bookName: 'Psalms', chapter: 116 }, { bookName: 'Psalms', chapter: 117 }, { bookName: 'Psalms', chapter: 118 },
    { bookName: 'Psalms', chapter: 119 }, { bookName: 'Psalms', chapter: 121 }, { bookName: 'Psalms', chapter: 122 },
    { bookName: 'Psalms', chapter: 126 }, { bookName: 'Psalms', chapter: 127 }, { bookName: 'Psalms', chapter: 128 },
    { bookName: 'Psalms', chapter: 133 }, { bookName: 'Psalms', chapter: 137 }, { bookName: 'Psalms', chapter: 139 },
    { bookName: 'Psalms', chapter: 145 }, { bookName: 'Psalms', chapter: 146 }, { bookName: 'Psalms', chapter: 147 },
    { bookName: 'Psalms', chapter: 148 }, { bookName: 'Psalms', chapter: 149 }, { bookName: 'Psalms', chapter: 150 },
    // New Testament - Gospels
    { bookName: 'Luke', chapter: 1 }, { bookName: 'Luke', chapter: 2 },
    { bookName: 'Matthew', chapter: 1 }, { bookName: 'Matthew', chapter: 2 },
    { bookName: 'Mark', chapter: 1 },
    { bookName: 'John', chapter: 1 },
    { bookName: 'Matthew', chapter: 3 }, { bookName: 'Mark', chapter: 1 }, { bookName: 'Luke', chapter: 3 },
    { bookName: 'Matthew', chapter: 4 }, { bookName: 'Luke', chapter: 4 }, { bookName: 'Luke', chapter: 5 },
    { bookName: 'John', chapter: 2 }, { bookName: 'John', chapter: 3 }, { bookName: 'John', chapter: 4 },
    { bookName: 'Mark', chapter: 2 }, { bookName: 'Matthew', chapter: 5 }, { bookName: 'Matthew', chapter: 6 },
    { bookName: 'Matthew', chapter: 7 }, { bookName: 'Luke', chapter: 6 }, { bookName: 'Luke', chapter: 7 },
    { bookName: 'Matthew', chapter: 8 }, { bookName: 'Mark', chapter: 3 }, { bookName: 'Matthew', chapter: 9 },
    { bookName: 'Matthew', chapter: 10 }, { bookName: 'Mark', chapter: 4 }, { bookName: 'Luke', chapter: 8 },
    { bookName: 'Matthew', chapter: 11 }, { bookName: 'Luke', chapter: 9 }, { bookName: 'Matthew', chapter: 12 },
    { bookName: 'Matthew', chapter: 13 }, { bookName: 'Mark', chapter: 5 }, { bookName: 'Mark', chapter: 6 },
    { bookName: 'John', chapter: 5 }, { bookName: 'John', chapter: 6 }, { bookName: 'Matthew', chapter: 14 },
    { bookName: 'Matthew', chapter: 15 }, { bookName: 'Mark', chapter: 7 }, { bookName: 'Matthew', chapter: 16 },
    { bookName: 'Mark', chapter: 8 }, { bookName: 'Matthew', chapter: 17 }, { bookName: 'Mark', chapter: 9 },
    { bookName: 'Luke', chapter: 10 }, { bookName: 'Luke', chapter: 11 }, { bookName: 'Luke', chapter: 12 },
    { bookName: 'Luke', chapter: 13 }, { bookName: 'John', chapter: 7 }, { bookName: 'John', chapter: 8 },
    { bookName: 'John', chapter: 9 }, { bookName: 'John', chapter: 10 }, { bookName: 'Luke', chapter: 14 },
    { bookName: 'Luke', chapter: 15 }, { bookName: 'Luke', chapter: 16 }, { bookName: 'Luke', chapter: 17 },
    { bookName: 'John', chapter: 11 }, { bookName: 'Luke', chapter: 18 }, { bookName: 'Matthew', chapter: 18 },
    { bookName: 'Matthew', chapter: 19 }, { bookName: 'Mark', chapter: 10 }, { bookName: 'Matthew', chapter: 20 },
    { bookName: 'Luke', chapter: 19 }, { bookName: 'Mark', chapter: 11 }, { bookName: 'Matthew', chapter: 21 },
    { bookName: 'John', chapter: 12 }, { bookName: 'Matthew', chapter: 22 }, { bookName: 'Mark', chapter: 12 },
    { bookName: 'Luke', chapter: 20 }, { bookName: 'Matthew', chapter: 23 }, { bookName: 'Luke', chapter: 21 },
    { bookName: 'Mark', chapter: 13 }, { bookName: 'Matthew', chapter: 24 }, { bookName: 'Matthew', chapter: 25 },
    { bookName: 'Matthew', chapter: 26 }, { bookName: 'Mark', chapter: 14 }, { bookName: 'Luke', chapter: 22 },
    { bookName: 'John', chapter: 13 }, { bookName: 'John', chapter: 14 }, { bookName: 'John', chapter: 15 },
    { bookName: 'John', chapter: 16 }, { bookName: 'John', chapter: 17 }, { bookName: 'John', chapter: 18 },
    { bookName: 'Matthew', chapter: 27 }, { bookName: 'Mark', chapter: 15 }, { bookName: 'Luke', chapter: 23 },
    { bookName: 'John', chapter: 19 }, { bookName: 'Matthew', chapter: 28 }, { bookName: 'Mark', chapter: 16 },
    { bookName: 'Luke', chapter: 24 }, { bookName: 'John', chapter: 20 }, { bookName: 'John', chapter: 21 },
    // Acts and Epistles
    { bookName: 'Acts', chapter: 1 }, { bookName: 'Acts', chapter: 2 }, { bookName: 'Acts', chapter: 3 },
    { bookName: 'Acts', chapter: 4 }, { bookName: 'Acts', chapter: 5 }, { bookName: 'Acts', chapter: 6 },
    { bookName: 'Acts', chapter: 7 }, { bookName: 'Acts', chapter: 8 }, { bookName: 'Acts', chapter: 9 },
    { bookName: 'Acts', chapter: 10 }, { bookName: 'Acts', chapter: 11 }, { bookName: 'Acts', chapter: 12 },
    { bookName: 'James', chapter: 1 }, { bookName: 'James', chapter: 2 }, { bookName: 'James', chapter: 3 },
    { bookName: 'James', chapter: 4 }, { bookName: 'James', chapter: 5 },
    { bookName: 'Acts', chapter: 13 }, { bookName: 'Acts', chapter: 14 },
    { bookName: 'Galatians', chapter: 1 }, { bookName: 'Galatians', chapter: 2 }, { bookName: 'Galatians', chapter: 3 },
    { bookName: 'Galatians', chapter: 4 }, { bookName: 'Galatians', chapter: 5 }, { bookName: 'Galatians', chapter: 6 },
    { bookName: 'Acts', chapter: 15 }, { bookName: 'Acts', chapter: 16 },
    { bookName: '1 Thessalonians', chapter: 1 }, { bookName: '1 Thessalonians', chapter: 2 }, { bookName: '1 Thessalonians', chapter: 3 },
    { bookName: '1 Thessalonians', chapter: 4 }, { bookName: '1 Thessalonians', chapter: 5 },
    { bookName: '2 Thessalonians', chapter: 1 }, { bookName: '2 Thessalonians', chapter: 2 }, { bookName: '2 Thessalonians', chapter: 3 },
    { bookName: 'Acts', chapter: 17 }, { bookName: 'Acts', chapter: 18 },
    { bookName: '1 Corinthians', chapter: 1 }, { bookName: '1 Corinthians', chapter: 2 }, { bookName: '1 Corinthians', chapter: 3 },
    { bookName: '1 Corinthians', chapter: 4 }, { bookName: '1 Corinthians', chapter: 5 }, { bookName: '1 Corinthians', chapter: 6 },
    { bookName: '1 Corinthians', chapter: 7 }, { bookName: '1 Corinthians', chapter: 8 }, { bookName: '1 Corinthians', chapter: 9 },
    { bookName: '1 Corinthians', chapter: 10 }, { bookName: '1 Corinthians', chapter: 11 }, { bookName: '1 Corinthians', chapter: 12 },
    { bookName: '1 Corinthians', chapter: 13 }, { bookName: '1 Corinthians', chapter: 14 }, { bookName: '1 Corinthians', chapter: 15 },
    { bookName: '1 Corinthians', chapter: 16 },
    { bookName: '2 Corinthians', chapter: 1 }, { bookName: '2 Corinthians', chapter: 2 }, { bookName: '2 Corinthians', chapter: 3 },
    { bookName: '2 Corinthians', chapter: 4 }, { bookName: '2 Corinthians', chapter: 5 }, { bookName: '2 Corinthians', chapter: 6 },
    { bookName: '2 Corinthians', chapter: 7 }, { bookName: '2 Corinthians', chapter: 8 }, { bookName: '2 Corinthians', chapter: 9 },
    { bookName: '2 Corinthians', chapter: 10 }, { bookName: '2 Corinthians', chapter: 11 }, { bookName: '2 Corinthians', chapter: 12 },
    { bookName: '2 Corinthians', chapter: 13 },
    { bookName: 'Acts', chapter: 19 },
    { bookName: 'Romans', chapter: 1 }, { bookName: 'Romans', chapter: 2 }, { bookName: 'Romans', chapter: 3 },
    { bookName: 'Romans', chapter: 4 }, { bookName: 'Romans', chapter: 5 }, { bookName: 'Romans', chapter: 6 },
    { bookName: 'Romans', chapter: 7 }, { bookName: 'Romans', chapter: 8 }, { bookName: 'Romans', chapter: 9 },
    { bookName: 'Romans', chapter: 10 }, { bookName: 'Romans', chapter: 11 }, { bookName: 'Romans', chapter: 12 },
    { bookName: 'Romans', chapter: 13 }, { bookName: 'Romans', chapter: 14 }, { bookName: 'Romans', chapter: 15 },
    { bookName: 'Romans', chapter: 16 },
    { bookName: 'Acts', chapter: 20 }, { bookName: 'Acts', chapter: 21 }, { bookName: 'Acts', chapter: 22 },
    { bookName: 'Acts', chapter: 23 }, { bookName: 'Acts', chapter: 24 }, { bookName: 'Acts', chapter: 25 },
    { bookName: 'Acts', chapter: 26 }, { bookName: 'Acts', chapter: 27 }, { bookName: 'Acts', chapter: 28 },
    { bookName: 'Ephesians', chapter: 1 }, { bookName: 'Ephesians', chapter: 2 }, { bookName: 'Ephesians', chapter: 3 },
    { bookName: 'Ephesians', chapter: 4 }, { bookName: 'Ephesians', chapter: 5 }, { bookName: 'Ephesians', chapter: 6 },
    { bookName: 'Philippians', chapter: 1 }, { bookName: 'Philippians', chapter: 2 }, { bookName: 'Philippians', chapter: 3 },
    { bookName: 'Philippians', chapter: 4 },
    { bookName: 'Colossians', chapter: 1 }, { bookName: 'Colossians', chapter: 2 }, { bookName: 'Colossians', chapter: 3 },
    { bookName: 'Colossians', chapter: 4 },
    { bookName: 'Philemon', chapter: 1 },
    { bookName: '1 Timothy', chapter: 1 }, { bookName: '1 Timothy', chapter: 2 }, { bookName: '1 Timothy', chapter: 3 },
    { bookName: '1 Timothy', chapter: 4 }, { bookName: '1 Timothy', chapter: 5 }, { bookName: '1 Timothy', chapter: 6 },
    { bookName: 'Titus', chapter: 1 }, { bookName: 'Titus', chapter: 2 }, { bookName: 'Titus', chapter: 3 },
    { bookName: '2 Timothy', chapter: 1 }, { bookName: '2 Timothy', chapter: 2 }, { bookName: '2 Timothy', chapter: 3 },
    { bookName: '2 Timothy', chapter: 4 },
    { bookName: '1 Peter', chapter: 1 }, { bookName: '1 Peter', chapter: 2 }, { bookName: '1 Peter', chapter: 3 },
    { bookName: '1 Peter', chapter: 4 }, { bookName: '1 Peter', chapter: 5 },
    { bookName: '2 Peter', chapter: 1 }, { bookName: '2 Peter', chapter: 2 }, { bookName: '2 Peter', chapter: 3 },
    { bookName: 'Hebrews', chapter: 1 }, { bookName: 'Hebrews', chapter: 2 }, { bookName: 'Hebrews', chapter: 3 },
    { bookName: 'Hebrews', chapter: 4 }, { bookName: 'Hebrews', chapter: 5 }, { bookName: 'Hebrews', chapter: 6 },
    { bookName: 'Hebrews', chapter: 7 }, { bookName: 'Hebrews', chapter: 8 }, { bookName: 'Hebrews', chapter: 9 },
    { bookName: 'Hebrews', chapter: 10 }, { bookName: 'Hebrews', chapter: 11 }, { bookName: 'Hebrews', chapter: 12 },
    { bookName: 'Hebrews', chapter: 13 },
    { bookName: 'Jude', chapter: 1 },
    { bookName: '1 John', chapter: 1 }, { bookName: '1 John', chapter: 2 }, { bookName: '1 John', chapter: 3 },
    { bookName: '1 John', chapter: 4 }, { bookName: '1 John', chapter: 5 },
    { bookName: '2 John', chapter: 1 },
    { bookName: '3 John', chapter: 1 },
    { bookName: 'Revelation', chapter: 1 }, { bookName: 'Revelation', chapter: 2 }, { bookName: 'Revelation', chapter: 3 },
    { bookName: 'Revelation', chapter: 4 }, { bookName: 'Revelation', chapter: 5 }, { bookName: 'Revelation', chapter: 6 },
    { bookName: 'Revelation', chapter: 7 }, { bookName: 'Revelation', chapter: 8 }, { bookName: 'Revelation', chapter: 9 },
    { bookName: 'Revelation', chapter: 10 }, { bookName: 'Revelation', chapter: 11 }, { bookName: 'Revelation', chapter: 12 },
    { bookName: 'Revelation', chapter: 13 }, { bookName: 'Revelation', chapter: 14 }, { bookName: 'Revelation', chapter: 15 },
    { bookName: 'Revelation', chapter: 16 }, { bookName: 'Revelation', chapter: 17 }, { bookName: 'Revelation', chapter: 18 },
    { bookName: 'Revelation', chapter: 19 }, { bookName: 'Revelation', chapter: 20 }, { bookName: 'Revelation', chapter: 21 },
    { bookName: 'Revelation', chapter: 22 },
  ],
  CHRONOLOGICAL_GOSPELS: [
    // Birth and Early Years
    { bookName: 'Luke', chapter: 1 }, { bookName: 'Matthew', chapter: 1 },
    { bookName: 'Luke', chapter: 2 }, { bookName: 'Matthew', chapter: 2 },
    // Preparation and Beginning of Ministry
    { bookName: 'Matthew', chapter: 3 }, { bookName: 'Mark', chapter: 1 }, { bookName: 'Luke', chapter: 3 },
    { bookName: 'Matthew', chapter: 4 }, { bookName: 'Luke', chapter: 4 },
    { bookName: 'John', chapter: 1 }, { bookName: 'John', chapter: 2 },
    // Early Galilean Ministry
    { bookName: 'John', chapter: 3 }, { bookName: 'John', chapter: 4 },
    { bookName: 'Mark', chapter: 1 }, { bookName: 'Luke', chapter: 4 }, { bookName: 'Luke', chapter: 5 },
    { bookName: 'Mark', chapter: 2 }, { bookName: 'Matthew', chapter: 9 },
    { bookName: 'John', chapter: 5 },
    // Sermon on the Mount and Teachings
    { bookName: 'Matthew', chapter: 5 }, { bookName: 'Matthew', chapter: 6 }, { bookName: 'Matthew', chapter: 7 },
    { bookName: 'Luke', chapter: 6 }, { bookName: 'Luke', chapter: 7 },
    { bookName: 'Matthew', chapter: 8 },
    // Growing Ministry and Miracles
    { bookName: 'Mark', chapter: 3 }, { bookName: 'Matthew', chapter: 12 },
    { bookName: 'Mark', chapter: 4 }, { bookName: 'Matthew', chapter: 13 }, { bookName: 'Luke', chapter: 8 },
    { bookName: 'Mark', chapter: 5 }, { bookName: 'Matthew', chapter: 9 },
    { bookName: 'Matthew', chapter: 10 }, { bookName: 'Mark', chapter: 6 },
    { bookName: 'Matthew', chapter: 14 }, { bookName: 'John', chapter: 6 },
    // Conflicts and Withdrawal
    { bookName: 'Matthew', chapter: 15 }, { bookName: 'Mark', chapter: 7 },
    { bookName: 'Matthew', chapter: 16 }, { bookName: 'Mark', chapter: 8 },
    { bookName: 'Matthew', chapter: 17 }, { bookName: 'Mark', chapter: 9 }, { bookName: 'Luke', chapter: 9 },
    { bookName: 'Matthew', chapter: 18 },
    // Journey to Jerusalem
    { bookName: 'John', chapter: 7 }, { bookName: 'John', chapter: 8 },
    { bookName: 'Luke', chapter: 10 }, { bookName: 'Luke', chapter: 11 },
    { bookName: 'Luke', chapter: 12 }, { bookName: 'Luke', chapter: 13 },
    { bookName: 'John', chapter: 9 }, { bookName: 'John', chapter: 10 },
    { bookName: 'Luke', chapter: 14 }, { bookName: 'Luke', chapter: 15 },
    { bookName: 'Luke', chapter: 16 }, { bookName: 'Luke', chapter: 17 },
    { bookName: 'John', chapter: 11 },
    // Final Journey and Entry
    { bookName: 'Luke', chapter: 18 }, { bookName: 'Matthew', chapter: 19 }, { bookName: 'Mark', chapter: 10 },
    { bookName: 'Matthew', chapter: 20 }, { bookName: 'Luke', chapter: 19 },
    { bookName: 'Mark', chapter: 11 }, { bookName: 'Matthew', chapter: 21 },
    { bookName: 'John', chapter: 12 },
    // Final Week - Teaching in Jerusalem
    { bookName: 'Matthew', chapter: 22 }, { bookName: 'Mark', chapter: 12 }, { bookName: 'Luke', chapter: 20 },
    { bookName: 'Matthew', chapter: 23 }, { bookName: 'Luke', chapter: 21 },
    { bookName: 'Mark', chapter: 13 }, { bookName: 'Matthew', chapter: 24 }, { bookName: 'Matthew', chapter: 25 },
    // Last Supper and Upper Room
    { bookName: 'Matthew', chapter: 26 }, { bookName: 'Mark', chapter: 14 }, { bookName: 'Luke', chapter: 22 },
    { bookName: 'John', chapter: 13 }, { bookName: 'John', chapter: 14 },
    { bookName: 'John', chapter: 15 }, { bookName: 'John', chapter: 16 }, { bookName: 'John', chapter: 17 },
    // Arrest and Trials
    { bookName: 'Matthew', chapter: 26 }, { bookName: 'Mark', chapter: 14 }, { bookName: 'Luke', chapter: 22 },
    { bookName: 'John', chapter: 18 },
    // Crucifixion
    { bookName: 'Matthew', chapter: 27 }, { bookName: 'Mark', chapter: 15 },
    { bookName: 'Luke', chapter: 23 }, { bookName: 'John', chapter: 19 },
    // Resurrection and Appearances
    { bookName: 'Matthew', chapter: 28 }, { bookName: 'Mark', chapter: 16 },
    { bookName: 'Luke', chapter: 24 }, { bookName: 'John', chapter: 20 }, { bookName: 'John', chapter: 21 },
  ],
};
