export const CURATED_PLANS = {
  LEADERSHIP_30: [
    { bookName: '1 Timothy', chapter: 1 },
    { bookName: '1 Timothy', chapter: 2 },
    { bookName: '1 Timothy', chapter: 3 },
    { bookName: '1 Timothy', chapter: 4 },
    { bookName: '1 Timothy', chapter: 5 },
    { bookName: '1 Timothy', chapter: 6 },
    { bookName: '2 Timothy', chapter: 1 },
    { bookName: '2 Timothy', chapter: 2 },
    { bookName: '2 Timothy', chapter: 3 },
    { bookName: '2 Timothy', chapter: 4 },
    { bookName: 'Titus', chapter: 1 },
    { bookName: 'Titus', chapter: 2 },
    { bookName: 'Titus', chapter: 3 },
    { bookName: 'Philemon', chapter: 1 },
    { bookName: 'James', chapter: 1 },
    { bookName: 'James', chapter: 2 },
    { bookName: 'James', chapter: 3 },
    { bookName: 'James', chapter: 4 },
    { bookName: 'James', chapter: 5 },
    { bookName: '1 Peter', chapter: 1 },
    { bookName: '1 Peter', chapter: 2 },
    { bookName: '1 Peter', chapter: 3 },
    { bookName: '1 Peter', chapter: 4 },
    { bookName: '1 Peter', chapter: 5 },
    { bookName: '2 Peter', chapter: 1 },
    { bookName: '2 Peter', chapter: 2 },
    { bookName: '2 Peter', chapter: 3 },
    { bookName: 'Jude', chapter: 1 },
    { bookName: 'Proverbs', chapter: 1 },
    { bookName: 'Proverbs', chapter: 2 },
  ],
  WISDOM_7: [
    { bookName: 'Proverbs', chapter: 1 },
    { bookName: 'Proverbs', chapter: 2 },
    { bookName: 'Proverbs', chapter: 3 },
    { bookName: 'Proverbs', chapter: 4 },
    { bookName: 'Ecclesiastes', chapter: 1 },
    { bookName: 'Ecclesiastes', chapter: 2 },
    { bookName: 'James', chapter: 1 },
  ],
};