export const BIBLE_BOOKS = [
  // Old Testament
  { name: "Genesis", chapters: 50, testament: "old", index: 0 },
  { name: "Exodus", chapters: 40, testament: "old", index: 1 },
  { name: "Leviticus", chapters: 27, testament: "old", index: 2 },
  { name: "Numbers", chapters: 36, testament: "old", index: 3 },
  { name: "Deuteronomy", chapters: 34, testament: "old", index: 4 },
  { name: "Joshua", chapters: 24, testament: "old", index: 5 },
  { name: "Judges", chapters: 21, testament: "old", index: 6 },
  { name: "Ruth", chapters: 4, testament: "old", index: 7 },
  { name: "1 Samuel", chapters: 31, testament: "old", index: 8 },
  { name: "2 Samuel", chapters: 24, testament: "old", index: 9 },
  { name: "1 Kings", chapters: 22, testament: "old", index: 10 },
  { name: "2 Kings", chapters: 25, testament: "old", index: 11 },
  { name: "1 Chronicles", chapters: 29, testament: "old", index: 12 },
  { name: "2 Chronicles", chapters: 36, testament: "old", index: 13 },
  { name: "Ezra", chapters: 10, testament: "old", index: 14 },
  { name: "Nehemiah", chapters: 13, testament: "old", index: 15 },
  { name: "Esther", chapters: 10, testament: "old", index: 16 },
  { name: "Job", chapters: 42, testament: "old", index: 17 },
  { name: "Psalms", chapters: 150, testament: "old", index: 18 },
  { name: "Proverbs", chapters: 31, testament: "old", index: 19 },
  { name: "Ecclesiastes", chapters: 12, testament: "old", index: 20 },
  { name: "Song of Solomon", chapters: 8, testament: "old", index: 21 },
  { name: "Isaiah", chapters: 66, testament: "old", index: 22 },
  { name: "Jeremiah", chapters: 52, testament: "old", index: 23 },
  { name: "Lamentations", chapters: 5, testament: "old", index: 24 },
  { name: "Ezekiel", chapters: 48, testament: "old", index: 25 },
  { name: "Daniel", chapters: 12, testament: "old", index: 26 },
  { name: "Hosea", chapters: 14, testament: "old", index: 27 },
  { name: "Joel", chapters: 3, testament: "old", index: 28 },
  { name: "Amos", chapters: 9, testament: "old", index: 29 },
  { name: "Obadiah", chapters: 1, testament: "old", index: 30 },
  { name: "Jonah", chapters: 4, testament: "old", index: 31 },
  { name: "Micah", chapters: 7, testament: "old", index: 32 },
  { name: "Nahum", chapters: 3, testament: "old", index: 33 },
  { name: "Habakkuk", chapters: 3, testament: "old", index: 34 },
  { name: "Zephaniah", chapters: 3, testament: "old", index: 35 },
  { name: "Haggai", chapters: 2, testament: "old", index: 36 },
  { name: "Zechariah", chapters: 14, testament: "old", index: 37 },
  { name: "Malachi", chapters: 4, testament: "old", index: 38 },
  // New Testament
  { name: "Matthew", chapters: 28, testament: "new", index: 39 },
  { name: "Mark", chapters: 16, testament: "new", index: 40 },
  { name: "Luke", chapters: 24, testament: "new", index: 41 },
  { name: "John", chapters: 21, testament: "new", index: 42 },
  { name: "Acts", chapters: 28, testament: "new", index: 43 },
  { name: "Romans", chapters: 16, testament: "new", index: 44 },
  { name: "1 Corinthians", chapters: 16, testament: "new", index: 45 },
  { name: "2 Corinthians", chapters: 13, testament: "new", index: 46 },
  { name: "Galatians", chapters: 6, testament: "new", index: 47 },
  { name: "Ephesians", chapters: 6, testament: "new", index: 48 },
  { name: "Philippians", chapters: 4, testament: "new", index: 49 },
  { name: "Colossians", chapters: 4, testament: "new", index: 50 },
  { name: "1 Thessalonians", chapters: 5, testament: "new", index: 51 },
  { name: "2 Thessalonians", chapters: 3, testament: "new", index: 52 },
  { name: "1 Timothy", chapters: 6, testament: "new", index: 53 },
  { name: "2 Timothy", chapters: 4, testament: "new", index: 54 },
  { name: "Titus", chapters: 3, testament: "new", index: 55 },
  { name: "Philemon", chapters: 1, testament: "new", index: 56 },
  { name: "Hebrews", chapters: 13, testament: "new", index: 57 },
  { name: "James", chapters: 5, testament: "new", index: 58 },
  { name: "1 Peter", chapters: 5, testament: "new", index: 59 },
  { name: "2 Peter", chapters: 3, testament: "new", index: 60 },
  { name: "1 John", chapters: 5, testament: "new", index: 61 },
  { name: "2 John", chapters: 1, testament: "new", index: 62 },
  { name: "3 John", chapters: 1, testament: "new", index: 63 },
  { name: "Jude", chapters: 1, testament: "new", index: 64 },
  { name: "Revelation", chapters: 22, testament: "new", index: 65 },
];

export const ACHIEVEMENTS = [
  { id: "first_chapter", name: "First Step", description: "Read your first chapter", icon: "🌱", condition: (stats) => stats.totalChaptersRead >= 1 },
  { id: "first_book", name: "Book Worm", description: "Complete your first book", icon: "📖", condition: (stats) => stats.totalBooksCompleted >= 1 },
  { id: "genesis_complete", name: "In The Beginning", description: "Complete Genesis", icon: "🌍", condition: (stats, books) => books.find(b => b.book_name === "Genesis")?.completion_count >= 1 },
  { id: "psalms_complete", name: "Psalmist", description: "Complete all 150 Psalms", icon: "🎵", condition: (stats, books) => books.find(b => b.book_name === "Psalms")?.completion_count >= 1 },
  { id: "gospels_complete", name: "Gospel Truth", description: "Complete all four Gospels", icon: "✝️", condition: (stats, books) => {
    const gospels = ["Matthew", "Mark", "Luke", "John"];
    return gospels.every(g => books.find(b => b.book_name === g)?.completion_count >= 1);
  }},
  { id: "old_testament", name: "Ancient Wisdom", description: "Complete the Old Testament", icon: "📜", condition: (stats) => stats.oldTestamentComplete >= 1 },
  { id: "new_testament", name: "New Covenant", description: "Complete the New Testament", icon: "💫", condition: (stats) => stats.newTestamentComplete >= 1 },
  { id: "full_bible", name: "Word Complete", description: "Read the entire Bible", icon: "👑", condition: (stats) => stats.fullBibleComplete >= 1 },
  { id: "ten_books", name: "Dedicated Reader", description: "Complete 10 books total", icon: "📚", condition: (stats) => stats.totalBooksCompleted >= 10 },
  { id: "twenty_five_books", name: "Scholar", description: "Complete 25 books total", icon: "🎓", condition: (stats) => stats.totalBooksCompleted >= 25 },
  { id: "fifty_completions", name: "Devotee", description: "Complete 50 books total", icon: "🏆", condition: (stats) => stats.totalBooksCompleted >= 50 },
  { id: "hundred_completions", name: "Bible Master", description: "Complete 100 books total", icon: "💎", condition: (stats) => stats.totalBooksCompleted >= 100 },
  { id: "double_bible", name: "Twice Through", description: "Complete the Bible twice", icon: "🌟", condition: (stats) => stats.fullBibleComplete >= 2 },
  { id: "revelation_complete", name: "The End", description: "Complete Revelation", icon: "🔮", condition: (stats, books) => books.find(b => b.book_name === "Revelation")?.completion_count >= 1 },
  { id: "pentateuch", name: "Torah Reader", description: "Complete the first 5 books", icon: "⚖️", condition: (stats, books) => {
    const pentateuch = ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"];
    return pentateuch.every(p => books.find(b => b.book_name === p)?.completion_count >= 1);
  }},
];

export const TOTAL_CHAPTERS = 1189;
export const OLD_TESTAMENT_BOOKS = 39;
export const NEW_TESTAMENT_BOOKS = 27;